### ISSUE TITLE
连续几张图片放大，有的图片出现问题

### ISSUE THREAD

**Issue by LDNew** [QuintGao/GKPhotoBrowser#1]
连续几张图片放大，有的图片出现问题

**Comment by heyehao2008** [comment]
确实有这个bug，查看图片时，每张图片都双击放大显示，在滑动查看其它图片。超过三四次后面的图片就会缩小，尺寸不正确，还没时间看源码，估计是cell重用将某个状态保留了

**Comment by QuintGao** [comment]
您好，问题已修复，请下载最新demo测试

**Comment by heyehao2008** [comment]
OK，该问题已经修复。

**Comment by lsmakethebest** [comment]
真难集成 依赖也是居多。集成进去得改好多地方，可以自己集成一下

**Comment by QuintGao** [comment]
@lsmakethebest 不知道你说的难集成是什么意思，整个框架就依赖了SDWebImage一个库，其他的都是为了写demo加上去的

**Comment by QuintGao** [comment]
集成时确实出现了一些问题，已经优化过了，
