### ISSUE TITLE
闪动问题

### ISSUE THREAD

**Issue by 18363853135** [QuintGao/GKPhotoBrowser#100]
第一次加载图片 会出现放大缩小的闪缩问题 ，猜测是第一次是加载了原图， 第二次是处理了图片 ，才造成了闪缩的效果，         browser.showStyle = .push 不会有闪缩问题， .zoom 和 .none 都有这个问题 请问下 怎么规避或者设置这个问题
SDWebImage 5.8.3  ios14  xcode12

**Comment by QuintGao** [comment]
我demo中有这个问题吗？

**Comment by LazyJiu** [comment]
> 我demo中有这个问题吗？

demo也有这个问题，demo中简书，会先放大在缩小，没有缓存的情况下，多试几次就能出现了

**Comment by LazyJiu** [comment]
![Untitled1](https://user-images.githubusercontent.com/18650229/100516270-ae6ea980-31bd-11eb-9f1d-d11b84eca8f2.gif)

**Comment by QuintGao** [comment]
你那是最新版吗，我试了没问题啊

**Comment by LazyJiu** [comment]
> 你那是最新版吗，我试了没问题啊

最新的，前两天刚下的，我找到问题了，你imageview的frame最开始是全屏，然后居中正方形，接着有图了之后，计算了大小，居中+实际大小。我觉得没有必要计算这么多次，imageview一开始不用给frame，等有图了之后计算一次就够，我把_imageView.frame         = CGRectMake(0, 0, GKScreenW, GKScreenH);

//        frame.origin        = CGPointZero;
//        CGFloat width       = frame.size.width;
//        CGFloat height      = width;
//        _imageView.bounds   = CGRectMake(0, 0, width, height);
//        _imageView.center   = CGPointMake(frame.size.width * 0.5, frame.size.height * 0.5);
//        // 重置内容大小
//        self.scrollView.contentSize = self.imageView.frame.size;
然后就正常了

**Comment by LazyJiu** [comment]
基本原因是imageView的frame多次变化造成的

**Comment by QuintGao** [comment]
嗯 确实有问题，我优化下

**Comment by 18363853135** [comment]
感谢回复  由于项目周期紧张  一直没仔细阅读代码或者回复邮件  这边出现的问题是browser.showStyle = .push 不会有闪缩问题， .zoom 和 .none 都有这个问题，希望有所建议
