### ISSUE TITLE
看多长图内存暴增

### ISSUE THREAD

**Issue by AppLog** [QuintGao/GKPhotoBrowser#101]
比如，我的一个目录有15张长图（1张图大概13M），通过组件进行预览，会发现，每切换一张图，就会内存增加200M左右，到总内存占用1G左右时，不再增加，但是图片也未能显示
![image](https://user-images.githubusercontent.com/343237/95826894-99e96580-0d65-11eb-9130-1bcd7c636007.png)
![IMG_3431](https://user-images.githubusercontent.com/343237/95826993-c1d8c900-0d65-11eb-972a-b09fc564009c.PNG)

**Comment by AppLog** [comment]
使用源主的demo项目，加上长图图片文件，能够复现该问题。

**Comment by QuintGao** [comment]
可否提供demo，我测试下

**Comment by AppLog** [comment]
后面发现问题了。我们从文件读取的image对象，被赋值给我们从外部传入的GKPhoto的image属性了。

**Comment by AppLog** [comment]
可以增加一个属性，用于决定是否将赋值。

**Comment by QuintGao** [comment]
最新版已优化
