### ISSUE TITLE
iOS14.2 本地 gif 显示是静态

### ISSUE THREAD

**Issue by gityoung** [QuintGao/GKPhotoBrowser#105]
RT
iOS 14.2
SDWebImage 5.9.0
YYWebImage 1.0.5

 GKPhoto *photo = [GKPhoto new];
 YYImage * gifImage = [YYImage imageWithData:info.localGif];
photo.image = gifImage;
photo.placeholderImage = gifImage;

**Comment by QuintGao** [comment]
最新demo已优化，可以查看TableViewCell多图zoom里面的使用。
