### ISSUE TITLE
iOS 14 不显示， SDWebImage 5.10.0 ， GKPhotoBrowser/SD 2.1.3

### ISSUE THREAD

**Issue by yuyunzhang** [QuintGao/GKPhotoBrowser#106]
SDWebImage 5.10.0 ， GKPhotoBrowser/SD 2.1.3 在iOS14上面不显示大图，点击会崩溃
![image](https://user-images.githubusercontent.com/13638600/102047289-f590a780-3e17-11eb-8fee-3ddc8b6e062c.png)

**Comment by QuintGao** [comment]
没太明白，你是怎么使用的？我的demo可以复现吗？

**Comment by iPermanent** [comment]
同样试过了iOS 14下就传了一下url数组进去黑的没法显示，SD 5.0.6版本,很简单就能复现出来的,用的最新版本

**Comment by QuintGao** [comment]
> 同样试过了iOS 14下就传了一下url数组进去黑的没法显示，SD 5.0.6版本,很简单就能复现出来的,用的最新版本

SD需要升级到5.8.3以上才可以

**Comment by QuintGao** [comment]
> 同样试过了iOS 14下就传了一下url数组进去黑的没法显示，SD 5.0.6版本,很简单就能复现出来的,用的最新版本

如果不想升级SD版本，也可以自定义图片加载类，实现GKWebImageProtocol协议，但是对GIF图片显示就有问题。
