### ISSUE TITLE
能不能增加保存按钮，保存到系统相册

### ISSUE THREAD

**Issue by wei287030375** [QuintGao/GKPhotoBrowser#107]
这个功能还是常见的，我现在是通过kvc加在contentView上。

        UIView *contentView = (UIView *)[_browser valueForKey:@"contentView"];
        UIButton *saveButton = [[UIButton alloc] init];
        saveButton.bounds = CGRectMake(0, 0, 50, 28);
        saveButton.layer.masksToBounds = YES;
        saveButton.layer.cornerRadius = 3;
        saveButton.backgroundColor = [UIColor baseColor_Current];
        CGFloat centerY = is_iPhoneX ? 54 : 30;
        
        UIDeviceOrientation currentOrientation = [UIDevice currentDevice].orientation;
        if (UIDeviceOrientationIsLandscape(currentOrientation)) {
            centerY = 30;
        }
        saveButton.center = CGPointMake(contentView.bounds.size.width * 0.9, centerY);
        [saveButton setTitle:@"保存" forState:UIControlStateNormal];
        [saveButton setTitleColor:[UIColor whiteColor] forState:UIControlStateNormal];
        [saveButton addTarget:self action:@selector(saveImageAction) forControlEvents:UIControlEventTouchUpInside];
        [contentView addSubview:saveButton];

**Comment by QuintGao** [comment]
这个有api的哈
- (void)setupCoverViews:(NSArray *)coverViews layoutBlock:(layoutBlock)layoutBlock;

**Comment by wei287030375** [comment]
这个api会跟页码label冲突，我加了保存按钮后原本的页码label不显示了，我还得在加个页码label

**Comment by QuintGao** [comment]
是的 这个是完全自定义，保存按钮的话，位置不好控制，还在自定义的好些。

**Comment by wei287030375** [comment]
好吧，我还是用kvc来加

**Comment by QuintGao** [comment]
最新版增加了保存按钮，可以通过设置显示保存按钮
 browser.hidesCountLabel = YES;
 browser.saveBtn.hidden = NO;
