### ISSUE TITLE
testflight生成的ipa安装后，点击图片预览崩溃

### ISSUE THREAD

**Issue by JCZ2014** [QuintGao/GKPhotoBrowser#116]
GKPhotoBrowser版本2.16，SDWebImage版本5.10.4。通过testflight生成的ipa安装后，点击图片预览崩溃。请问这个是什么问题造成的？是GKPhotoBrowser库哪里没有做兼容，还是其他库引起的

**Comment by QuintGao** [comment]
2.1.6版本有个bug，会导致release打包后，点击图片崩溃，请更新到2.1.7版本

**Comment by JCZ2014** [comment]
好的，我升级到最新版本试下

**Comment by JCZ2014** [comment]
升级到最新版本，之前的崩溃没有了，谢谢！
