### ISSUE TITLE
最新版图片无法显示

### ISSUE THREAD

**Issue by Mamakou** [QuintGao/GKPhotoBrowser#118]
用最新版的 图片无法显示图片，全部是黑色的，但是顶部白色的页码可以看到，其他全部是黑色，imageview有大小，也有image，目前还没发现问题所在

**Comment by Mamakou** [comment]
后来 我在GKSDWebImageManager类中修改了imageViewClass后就正常显示了，希望作者可以改进一下，我也看看啥问题

**Comment by Mamakou** [comment]
原来早就有人发现这个问题了，只需要在SDAnimatedImageView.m的- (void)displayLayer:(CALayer *)layer加一个super displayLayer就好了

**Comment by QuintGao** [comment]
你用的不是最新版SDWebImage吧

**Comment by binbins** [comment]
@Mamakou 感谢，解决了我的问题

**Comment by binbins** [comment]
环境SDWebImage v5.1.1  , GKPhotoBrowser v2.1.8

苹果7（系统14.0）出现了黑屏问题，奇怪的是苹果6s（13.5.1）没有这个问题，加了[super displayLayer:layer]之后好了

**Comment by JCZ2014** [comment]
> 你用的不是最新版SDWebImage

最新版SDWebImage会有问题么

**Comment by QuintGao** [comment]
iOS 14下UIKit对 `displayLayer:`的处理机制有所变化，SDWebImage需要升级到5.8.3以上或者就按照上面的方法修改也行

**Comment by QuintGao** [comment]
> > 你用的不是最新版SDWebImage吧
> 
> 最新版SDWebImage会有问题么

最新版没有问题的

**Comment by JCZ2014** [comment]
> > > 你用的不是最新版SDWebImage吧
> 
> > 
> 
> > 最新版SDWebImage会有问题么
> 
> 
> 
> 最新版没有问题的

我项目里SDWebImage 5.11.0，GKImageBrower 2.1.9 还是有问题。请问咋解😂

**Comment by JCZ2014** [comment]
> > > > 你用的不是最新版SDWebImage吧
> > 
> > > 
> > 
> > > 最新版SDWebImage会有问题么
> > 
> > 
> > 
> > 最新版没有问题的
> 
> 我项目里SDWebImage 5.11.0，GKImageBrower 2.1.9 还是有问题。请问咋解😂

升级到2.2.0就可以了，感谢作者！
