### ISSUE TITLE
图片放大，App挂起后返回图片不见/变小

### ISSUE THREAD

**Issue by JCZ2014** [QuintGao/GKPhotoBrowser#120]
软硬件环境：
1、GKImageBrower版本2.1.9；
2、SDWebImage版本5.11.0；
3、手机系统iOS 14.5 beta 8。

问题场景：
首先，点击图片预览，放大图片，App挂起到后台；
其次，App返回前台，此时App全屏广告弹出，点击查看广告详情（模态方式进入）；
接着，从广告详情返回图片预览时，之前预览图片不见或者点击变小了；
最后，怎样修改才能彻底解决呢？还请作者指点😂

**Comment by QuintGao** [comment]
最新版2.2.0已修复

**Comment by JCZ2014** [comment]
> 最新版2.2.0已修复

嗯，刚验证过了，已经被修复了。感谢！！！

**Comment by JCZ2014** [comment]
已经被作者修复
