### ISSUE TITLE
希望能优化下，默认实现单页时，pageControl隐藏

### ISSUE THREAD

**Issue by GentleForYou** [QuintGao/GKPhotoBrowser#124]
希望能优化下，默认实现单个图片预览时，pageControl隐藏；多个图片预览时，pageControl显示；

**Comment by JCZ2014** [comment]
Demo里微信朋友圈里有用到PageControl，显示还是隐藏PageControl自己处理一下就好。

**Comment by JCZ2014** [comment]
> 希望能优化下，默认实现单个图片预览时，pageControl隐藏；多个图片预览时，pageControl显示；

Demo里微信朋友圈里有用到PageControl，显示还是隐藏PageControl自己处理一下就好。

**Comment by QuintGao** [comment]
最新版已优化
