### ISSUE TITLE
请问如何自动加载原图

### ISSUE THREAD

**Issue by YoungXKing** [QuintGao/GKPhotoBrowser#125]
现在是必须实现loadImageAtIndex代理方法才能加载原图吧

**Comment by YoungXKing** [comment]
而且要设置loadStyle为GKPhotoBrowserLoadStyleCustom，代理方法才会执行

**Comment by QuintGao** [comment]
是的，这是一种方法。
还有一种就是不传缩略图，直接传原图

**Comment by YoungXKing** [comment]
> 是的，这是一种方法。
> 还有一种就是不传缩略图，直接传原图

好的，谢谢
