### ISSUE TITLE
iOS 11下加载多个gif图片卡顿、崩溃

### ISSUE THREAD

**Issue by Nevergive-up** [QuintGao/GKPhotoBrowser#129]
其他系统版本加载gif图片也是明显卡顿，内存比较低的手机直接崩溃

Message from debugger: Terminated due to memory issue
![image](https://user-images.githubusercontent.com/6007550/147182520-630ff9e5-d472-4970-8cc3-0b5ea98df238.png)

**Comment by QuintGao** [comment]
有测试demo吗

**Comment by Nevergive-up** [comment]
http://img.youluwx.com/files/20211222/images/2e938d76-5d37-4125-ad53-8df8c0cffc2f.gif
http://img.youluwx.com/files/20211222/images/bdb0102a-b213-4c59-9d33-8cb89c149120.gif
你那边试一下这两个图片，在我们的 iPhone X iOS11.3.1 上出现的

**Comment by monkeyRing** [comment]
> 

key

> 有测试demo吗

gif问题 可以看看这个  
https://www.jianshu.com/p/ec5e4acce654?utm_campaign=maleskine&utm_content=note&utm_medium=seo_notes&utm_source=recommendation
