### ISSUE TITLE
缩放返回背景不透明问题

### ISSUE THREAD

**Issue by huipengo** [QuintGao/GKPhotoBrowser#13]
作者，你好！
我修改以下方法，变成导航控制器，缩放返回的时候，背景不透明了

- (void)showFromVC:(UIViewController *)vc {
    
    self.fromVC = vc;
    
//    if (self.showStyle == GKPhotoBrowserShowStylePush) {
//        [vc.navigationController pushViewController:self animated:YES];
//    }else {
//        self.modalPresentationCapturesStatusBarAppearance = YES;
//        [vc presentViewController:self animated:NO completion:nil];
//    }
    UINavigationController *nav = [[UINavigationController alloc] initWithRootViewController:self];
    [vc presentViewController:nav animated:NO completion:nil];
}

**Comment by QuintGao** [comment]
![图片](https://user-images.githubusercontent.com/13514024/40598714-f57d4c32-627b-11e8-8923-5ff2fbcdbdf7.jpeg)
你好，可以通过上面的方式present出导航控制器。
刚刚通过视图层级检查了下，直接present出导航控制器，原来的控制器会被暂时移除，所以会导致背景不透明。

**Comment by QuintGao** [comment]
你好，刚刚试了下，直接present出导航控制器，导航控制器的view会被直接加在UIWindow上，原来的控制器应该被暂时移除了，所以导致背景不透明。

**Comment by huipengo** [comment]
嗯，多谢作者，我自己试了一些方法，还是没能解决~~~

**Comment by MrGuys** [comment]
改成UIModalPresentationFullScreen，就正常了
