### ISSUE TITLE
自定义图片加载类

### ISSUE THREAD

**Issue by wdq123550** [QuintGao/GKPhotoBrowser#137]
自定义图片加载类，如：SDWebImage 5.0以下版本，请使用pod 'GKPhotoBrowser/Core'，然后添加图片加载类并实现GKWebImageProtocol协议

我有一个第三方的SDK，他没有给出图片的url，而是通过一个API的block来回调得到image的。这种情况下。貌似本框架不支持指定以呢。可以加一个这个功能吗？

**Comment by QuintGao** [comment]
什么SDK
