### ISSUE TITLE
在iPad上查看大图，点击消失时会先放大图片再消失

### ISSUE THREAD

**Issue by JQHxx** [QuintGao/GKPhotoBrowser#138]

**Comment by JQHxx** [comment]
复现场景：
一个 cell上垂直方向上排列多张图， 查看大图是未设置隐藏样式
点击第一张图查看：变小消失
点击第二张图查看：变大消失
点击第三张图查看：变大消失
点击第四张图查看：slide动画消失
以上使用的是最新版本，设置hidestyle也不起作用

**Comment by JQHxx** [comment]
![QQ20220406-161537-HD](https://user-images.githubusercontent.com/16495357/161930055-eb3f1491-43be-4a20-b916-d0f01b8fa912.gif)

**Comment by QuintGao** [comment]
> 复现场景：
> 一个 cell上垂直方向上排列多张图， 横屏查看大图是未设置隐藏样式
> 点击第一张图查看：变小消失
> 点击第二张图查看：变大消失
> 点击第三张图查看：变大消失
> 点击第四张图查看：slide动画消失
> 以上使用的是最新版本，设置hidestyle也不起作用

这几步你调用的什么方法，没看懂你怎么调用的

**Comment by JQHxx** [comment]
[TestImagesDemo.zip](https://github.com/QuintGao/GKPhotoBrowser/files/8425572/TestImagesDemo.zip)

**Comment by JQHxx** [comment]
在iPad上运行，退出动画是随机的

**Comment by QuintGao** [comment]
[TestImagesDemo.zip](https://github.com/QuintGao/GKPhotoBrowser/files/8439081/TestImagesDemo.zip)
@JQHxx 改了下，看看是不是你想要的效果

**Comment by JQHxx** [comment]
是了，什么时候发版

**Comment by QuintGao** [comment]
已更新
