### ISSUE TITLE
点击图片GKPhotoView加载原图失败

### ISSUE THREAD

**Issue by AllenChen1988** [QuintGao/GKPhotoBrowser#140]
点击一张图片，originUrl是有的，缓存中没有这张图，在执行GKPhotoView->_imageProtocol(272行)之后，显示的还是缩略图，左右滑动之后加载又可以成功,之前版本好像没有这个问题，麻烦大佬看一下

**Comment by QuintGao** [comment]
我这没发现问题，我demo能复现吗

**Comment by AllenChen1988** [comment]
没有再加载一次

**Comment by Czing** [comment]
我的版本也出现同样的问题，加载原图后使用- (void)resetPhotoBrowserWithPhoto:(GKPhoto *)photo index:(NSInteger)index  去替换 无效
