### ISSUE TITLE
点击图片，状态栏上移

### ISSUE THREAD

**Issue by Nevergive-up** [QuintGao/GKPhotoBrowser#141]
iOS 15.0
iPhone 8 Plus
GKPhotoBrowser  2.3.8  2.3.3 两个版本使用
下面是录屏
https://user-images.githubusercontent.com/6007550/168416363-c777c185-e61b-40a4-8ecd-496ba91b2cf6.mp4

**Comment by QuintGao** [comment]
有属性可以控制状态栏不隐藏

**Comment by Nevergive-up** [comment]
> 有属性可以控制状态栏不隐藏
现在是默认隐藏状态，其他设备上面展示图片时候，不会影响我当前的 ViewController 状态栏，但是在上面所说的设备上，会造成外面状态栏的隐藏

**Comment by QuintGao** [comment]
这应该是系统的问题，不影响使用
