### ISSUE TITLE
我给了photo.sourceFrame，第一次还是没有动画

### ISSUE THREAD

**Issue by AllenChen1988** [QuintGao/GKPhotoBrowser#144]
这样赋值第一次查看没动画
photo.sourceImageView = view.mainImageView;
photo.sourceFrame = begainRect;
这样有动画，
photo.sourceImageView = view.mainImageView;
photo.image = view.mainImageView.image；
可是加载原图会有些问题，下载之后不显示原图了，不给这个值第一次点开就没有出现时的GKPhotoBrowserShowStyleZoom动画效果，我搞这定了，大佬请指教

**Comment by QuintGao** [comment]
有demo吗

**Comment by AllenChen1988** [comment]
没有demo，现在我取缓存判断有没有原图，缓存有我就直接再把Image给上赋值，不过多张大长图加载好像有点问题，不显示原图

**Comment by AllenChen1988** [comment]
左右滑动的时候

**Comment by QuintGao** [comment]
不要赋值给image，想要默认显示的话赋值给placeholderImage，还有问题的话最好写个demo，我好测试

**Comment by AllenChen1988** [comment]
我试过给placeholderImage，也是第一次没有动画，只有给了image才正常
  // 设置图片的frame
self.imageView.frame = imageF;
Thread 1: "CALayer position contains NaN: [187.5 nan]. Layer: <CALayer:0x2822015e0; position = CGPoint (187.5 1325.89); bounds = CGRect (0 0; 375 2651.79); delegate = <SDAnimatedImageView: 0x103639070; baseClass = UIImageView; frame = (0 0; 375 2651.79); clipsToBounds = YES; opaque = NO; userInteractionEnabled = NO; layer = <CALayer: 0x2822015e0>>; masksToBounds = YES; allowsGroupOpacity = YES; contentsMultiplyColor = (null)>"
有一张长图，加载原图的时候NAN闪退了
(lldb) po imageF
(origin = (x = 0, y = 0), size = (width = 375, height = NaN))
给了image的动画和加载都没问题了，现在就是这个有可能闪退，还有一个就是左右滑动，有加载过的原图会出现卡顿，我在查原因，你有什么建议给我吗

**Comment by QuintGao** [comment]
不要直接给image赋值，图片多的话会造成内存溢出，没有动画的情况我这里没遇到过，你看我demo能复现吗

**Comment by AllenChen1988** [comment]
> 

你的写法我和的不太一样，你的demo没这个问题，那我只给第一张image吧，现在就是从不是原图或没有加载的原图到已经加载的原图滑动会有点点卡

**Comment by QuintGao** [comment]
好吧 那你自己处理吧，不知道你怎么用的
