### ISSUE TITLE
加载200M的大图，会黑屏

### ISSUE THREAD

**Issue by QiaokeZ** [QuintGao/GKPhotoBrowser#146]
缩小一部分后，图片完全消失不见

**Comment by QuintGao** [comment]
图片链接发一下

**Comment by QiaokeZ** [comment]
https://pan.baidu.com/s/1mYa-nAsup1S69-zUMw5U9Q 提取码: tnqq

**Comment by QiaokeZ** [comment]
https://pan.baidu.com/s/1mYa-nAsup1S69-zUMw5U9Q 提取码: tnqq

**Comment by QuintGao** [comment]
没有链接吗，这个还得下载下来

**Comment by QiaokeZ** [comment]
这张图片保存到我们内网服务器，发不了， 麻烦你下载到本地看看

**Comment by QuintGao** [comment]
你这图片太大了，UIImageView设置的尺寸小了就会显示不了，你可以写个demo试试

**Comment by QiaokeZ** [comment]
能不能加一个方法，加载大图的时候，压缩图片到指定多少MB，要不然加载大图会导致内存暴增

**Comment by QuintGao** [comment]
可以自定义图片加载类，实现GKWebImageProtocol协议，在相应的方法中做处理
