### ISSUE TITLE
大神好，又来打扰了 UIDeviceOrientationFaceUp都被认为UIDeviceOrientationPortrait的问题

### ISSUE THREAD

**Issue by AllenChen1988** [QuintGao/GKPhotoBrowser#147]
因为UIDeviceOrientationFaceUp都被认为UIDeviceOrientationPortrait，当我横屏之后放在桌上看的时候，又会变成竖屏，可以有相关的改动给用户选择模式吗~谢谢

**Comment by QuintGao** [comment]
这里确实有问题，最新版已修复
