### ISSUE TITLE
GKPhotoView中的adjustFrame方法可能闪退问题

### ISSUE THREAD

**Issue by hegongdachen** [QuintGao/GKPhotoBrowser#151]
![VC20220922-170903](https://user-images.githubusercontent.com/5773584/191706908-1e3244a8-0128-4c3f-a1c2-708bc13eeaaf.png)

CGSize imageSize = self.imageView.image.size;
CGRect imageF = (CGRect){{0, 0}, imageSize};        
  // 图片的宽度 = 屏幕的宽度
 CGFloat ratio = frame.size.width / imageF.size.width;

此处的imageF.size.width 为0，计算后ratio为+Inf (无穷大)，导致下面赋值闪退
self.imageView.center = CGPointMake(self.scrollView.bounds.size.width * 0.5, imageF.size.height * 0.5);

**Comment by QuintGao** [comment]
已修复
