### ISSUE TITLE
是否能支技一下GIF图片

### ISSUE THREAD

**Issue by 1987zcc** [QuintGao/GKPhotoBrowser#157]
感谢作者的付出。

**Comment by QuintGao** [comment]
gif图片支持的
2.0.0之后修改了对gif图片的加载方式
1、使用SDWebImage(5.x)加载图片，请使用pod 'GKPhotoBrowser' 或 'GKPhotoBrowser/SD'
2、使用YYWebImage(1.0.5)加载图片，请使用pod 'GKPhotoBrowser/YY'
