### ISSUE TITLE
超长图加载模糊问题

### ISSUE THREAD

**Issue by iPermanent** [QuintGao/GKPhotoBrowser#159]
使用了以后一张1000*4302的长图，加载显示模糊，甚至没有加载原图的按钮，由于是公司内部图片禁止外传不方便给出url  但是应该很容易复现的

**Comment by QuintGao** [comment]
直接使用SDWebImage看看模糊吗

**Comment by iPermanent** [comment]
> 直接使用SDWebImage看看模糊吗

sd加载也是糊的，看了下是传了url和 originUrl ，如果直接给originUrl 是可以加载出高清图像但是同时传的话，只能加载模糊的缩略图，原图按钮不显示，以下是代码，主要是这个查看原图按钮不显示的问题，看了下接口好像也没有设置的选项，只有一个originLoadStyle 属性  注释写的不是很清楚

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/1712759/212835109-7bd152fe-a486-4495-9b7c-e67278b9022a.png">

**Comment by QuintGao** [comment]
查看原图按钮是需要自定义的，可以通过- (void)setupCoverViews:(NSArray *)coverViews layoutBlock:(layoutBlock)layoutBlock;方法添加，demo上有示例的
<img width="924" alt="image" src="https://user-images.githubusercontent.com/13514024/212836134-aea21d37-b36b-4ed9-9e89-c408c57b3e0a.png">

**Comment by iPermanent** [comment]
感谢，我去加上试试
