### ISSUE TITLE
可以自己设置SDWebImage的下载策略吗

### ISSUE THREAD

**Issue by ljbshishabi** [QuintGao/GKPhotoBrowser#160]
我在列表使用了[self.proImageV sd_setImageWithURL:[NSURL URLWithString:model.imgUrlList.firstObject] placeholderImage:[UIImage imageNamed:@"ab_logo"] options:SDWebImageRefreshCached context:@{SDWebImageContextImageThumbnailPixelSize:@(CGSizeMake(750, 750))}]

但是点击大图的时候应该是不使用缩略图的，所以能单独设置一下下载的策略吗

**Comment by QuintGao** [comment]
可以自定义图片加载类，pod 'GKPhotoBrowser/Core'，然后添加图片加载类并实现GKWebImageProtocol协议
