### ISSUE TITLE
缩略图和实际图片尺寸不一致，加载成功原图后变形的问题

### ISSUE THREAD

**Issue by iPermanent** [QuintGao/GKPhotoBrowser#164]
如标题所说，当一个图片比例过长或者过宽的时候，缩略图会使用裁剪后的图片，取中间的范围，如此处理以后，在点击加载原图以后，原图显示的比例依旧是按缩略图的来的导致图片被压缩的比较厉害，这个是否考虑做一下优化

**Comment by QuintGao** [comment]
怎么使用的，来个demo
