### ISSUE TITLE
提交审核被拒

### ISSUE THREAD

**Issue by BinBear** [QuintGao/GKPhotoBrowser#165]
<img width="678" alt="image" src="https://user-images.githubusercontent.com/13587915/224977752-8471648b-df07-4883-8263-1b51bfcebf44.png">

**Comment by QuintGao** [comment]
这么奇怪，我项目很多videoView都没提示这个，我换个名吧

**Comment by QuintGao** [comment]
试试最新版

**Comment by BinBear** [comment]
下个版本再试了，已经回滚到2.4.6重新提交了

**Comment by BinBear** [comment]
应该还是不行的，因为我只引入了core：pod 'GKPhotoBrowser/Core'
![image](https://user-images.githubusercontent.com/13587915/225373086-db8e0000-7c96-4e58-ba9f-4996b0a1a459.png)
而整个core中只有 GKVideoPlayerProtocol 协议有 videoView，这个地方没有改

**Comment by QuintGao** [comment]
已经改过了啊，2.5.1版本吗？

**Comment by BinBear** [comment]
建议 GKVideoPlayerProtocol 这个协议中的方法属性加上前缀（其他对外暴露的类也最好加上吧），不然很容易被误识别为私有API，大概率是与 AVPlayer 内部方法属性同名了，oc没有命名空间有时候就是这么蛋疼
