### ISSUE TITLE
打包上传看到一个警告

### ISSUE THREAD

**Issue by HelloHchen** [QuintGao/GKPhotoBrowser#166]
App Store Connect Operation Error
The app references non-public selectors in Payload/xxxxxx.app/Frameworks/GKPhotoBrowser.framework/GKPhotoBrowser: replay

说是调用了一个私有方法，但是项目好像没搜到

不知道会不会被拒。

**Comment by HelloHchen** [comment]
Xcode： 14.2
GKPhotoBrowser：2.5.2

**Comment by BinBear** [comment]
GKVideoPlayerProtocol 这个协议中的方法，有提示的话应该机审就会被拒，建议作者加上前缀，大概率跟AVPlayer有关
