### ISSUE TITLE
浏览视频，划出屏幕后再划回来，player下移

### ISSUE THREAD

**Issue by wyk190576528** [QuintGao/GKPhotoBrowser#168]
视频和图片混合浏览，视频划出，显示图片后，再次滑回到上一个视频后，视频的player下移，frame是在这个视频全部划出屏幕时改变的

**Comment by wyk190576528** [comment]
是因为视频的缩略图和视频的宽高比不一样

**Comment by QuintGao** [comment]
最新版已修复

**Comment by wyk190576528** [comment]
朋友圈的视频没问题了，但长图的显示有问题，长图显示后，操作放大，再滑到别的视频或图片，多滑几页，再回到长图页，会出现长图恢复到原来的缩小状态，还会出现黑屏不显示图片的情况

**Comment by QuintGao** [comment]
最新版已修复

**Comment by wyk190576528** [comment]
朋友圈模块里，点击第一个视频，播放没问题，左滑到第三个，也是视频，一直显示封面图，右滑回第一个视频，也是一直显示封面图。不显示视频的播放

**Comment by QuintGao** [comment]
修复了，看看还有问题吗

**Comment by wyk190576528** [comment]
第一个和第三个，来回切换，应该是没问题了，但第三个视频，左滑到第六个图片后，在右滑回第三个，视频的封面图一直显示

**Comment by wyk190576528** [comment]
没问题了
