### ISSUE TITLE
hidesPageControl 不生效

### ISSUE THREAD

**Issue by Mamakou** [QuintGao/GKPhotoBrowser#172]
希望作者能开放一个参数，hideWhenSingle，这样就无需再外面判断了。

**Comment by QuintGao** [comment]
没有不生效啊，你怎么使用的？

**Comment by Mamakou** [comment]
![image](https://github.com/QuintGao/GKPhotoBrowser/assets/13375024/0ec3faab-453f-4bca-905d-11a38c834f1f)
，我刚才更新到最新版了，发现底部的pageControl无法隐藏后，我又切回去了

**Comment by Lpkiki** [comment]
为什么这个pch文件里的头文件 全都 not found  ，想看demo 试了好多方法也不行
