### ISSUE TITLE
超大分辨率图会占用超大内存导致爆掉

### ISSUE THREAD

**Issue by iPermanent** [QuintGao/GKPhotoBrowser#174]
<img width="630" alt="image" src="https://github.com/QuintGao/GKPhotoBrowser/assets/1712759/aa4d0604-f609-4ae6-952b-d163ca0e4d0e">
测试用了一张20000多分辨率的图片，直接爆掉内存了，应该是里面sdanimatedView的问题，我觉得可以考虑使用CATiledLayer做一下优化，现在的库支持自己做这方面的定义吗  在不修改源码的情况下

**Comment by QuintGao** [comment]
可以自定义图片加载类，自定义一个UIImageView，然后用CATiledLayer显示图片

**Comment by QuintGao** [comment]
可以自定义图片加载类，自定义一个UIImageView，然后用CATiledLayer显示图片

**Comment by iPermanent** [comment]
<img width="2181" alt="image" src="https://github.com/QuintGao/GKPhotoBrowser/assets/1712759/9c2cbe86-44c7-404c-9fc0-f4ac1799094e">

使用 setupWebImageProtocol 设置了一个实现GKWebImageProtocol协议的类以后就crash了，imageViewClass 返回的是一个继承于UIImageView的类

**Comment by iPermanent** [comment]
试了一下自定义，只要重写了imageView class的 -(UIImage *)image 方法，就依旧会卡死，但是如果不写的话，需要里面调整宽高frame 会导致无法绽放等，zip里是代码
FPWebPhotoLoader *photoloader = [[FPWebPhotoLoader alloc] init];
[browser setupWebImageProtocol:photoloader];
[归档.zip](https://github.com/QuintGao/GKPhotoBrowser/files/11622481/default.zip)
![Fishpond_20230530172252](https://github.com/QuintGao/GKPhotoBrowser/assets/1712759/8a63edc7-97cc-4c85-a853-62ce5b10e2bc)

**Comment by iPermanent** [comment]
另外试用了一下视频播放功能，有以下两个问题
1.不显示进度条，hidesVideoSlider 这个不设置或者直接设置NO都不行
2.- (void)photoBrowser:(GKPhotoBrowser *)browser videoTimeChangeWithPhotoView:(GKPhotoView *)photoView
		 currentTime:(NSTimeInterval)currentTime
		   totalTime:(NSTimeInterval)totalTime
视频播放进度无回调
使用版本 pod 'GKPhotoBrowser/AVPlayer','2.5.9'

**Comment by QuintGao** [comment]
> 

怎么使用的，来个demo，我这里没问题

**Comment by iPermanent** [comment]
[FPPhotoBrowserDemo.zip](https://github.com/QuintGao/GKPhotoBrowser/files/11631741/FPPhotoBrowserDemo.zip)
试了下在demo工程里，因为只有一张大图按正常方式不修改可以加载，但是在工程里内存会爆掉，视频依旧是没有进度条显示
使用了自定义的image加载类以后内存crash，视频播放的进度回调可以正常收到

**Comment by iPermanent** [comment]
看过demo了  视频这块应该是还是要和图片查看原图一样加一个组件上去，我试一下

**Comment by QuintGao** [comment]
> 看过demo了 视频这块应该是还是要和图片查看原图一样加一个组件上去，我试一下

是的，如果使用setupCoverViews方法，内部会隐藏默认的控件如：进度条等，需要自己自定义添加

**Comment by iPermanent** [comment]
> > 看过demo了 视频这块应该是还是要和图片查看原图一样加一个组件上去，我试一下
> 
> 是的，如果使用setupCoverViews方法，内部会隐藏默认的控件如：进度条等，需要自己自定义添加

https://github.com/QuintGao/GKPhotoBrowser/assets/1712759/35ec64d8-7192-406a-a60b-2b3553894298


视频这块还是有点问题，参考demo加上的progressView 加上去以后，上面的不响应点击事件无法暂停和调整进度，这块我跟进源码里先看下，然后还有一个比较严重的问题是，在横屏下打开这个预览图片或者视频页面，都会界面错乱

**Comment by QuintGao** [comment]
最新版增加了加载大图的demo，看看有没有问题
