### ISSUE TITLE
回调方法index数组越界crash问题

### ISSUE THREAD

**Issue by iPermanent** [QuintGao/GKPhotoBrowser#175]
以下是crash日志，在方法里取phto自动显示原图时，越界了，由于是用户给出的crash日志无法跟踪复现，看情况像是将一个为负数值赋给NSUInteger类型的变量导致的数组越界
- (void)photoBrowser:(GKPhotoBrowser *)browser didSelectAtIndex:(NSInteger)index {
	GKPhoto *photo = [browser.photos objectAtIndex:index];
}

crash time : 2023-06-13 18:17:15:015 
name : NSRangeException 
reason : *** -[__NSArrayM objectAtIndex:]: index 9223372036854775807 beyond bounds [0 .. 39] 
userInfo : (null) 
stacks : (0x1d14e0cb4 0x1ca5883d0 0x1d1686f84 0x1d14f15dc 0x100566d00 0x1009927b8 0x100997ac0 0x100999690 0x1d45a6830 0x1d36148d8 0x1d3613834 0x1d3612f50 0x1d2a0e624 0x1d89a6eac 0x1d89b56a4 0x1d89b52f4 0x1d156fc28 0x1d1551560 0x1d15563ec 0x20ca1b35c 0x1d38e36e8 0x1d38e334c 0x1005513c8 0x1f0a56dec) 
call Symbols : (
	0   CoreFoundation                      0x00000001d14e0cc0 4230C122-42E8-383B-BEEC-EE7B61F8BB61 + 40128
	1   libobjc.A.dylib                     0x00000001ca5883d0 objc_exception_throw + 60
	2   CoreFoundation                      0x00000001d1686f84 4230C122-42E8-383B-BEEC-EE7B61F8BB61 + 1769348
	3   CoreFoundation                      0x00000001d14f15dc 4230C122-42E8-383B-BEEC-EE7B61F8BB61 + 107996
	4   FishPondIM                          0x0000000100566d00 -[FPPhotoBrowser photoBrowser:didSelectAtIndex:] + 100
	5   FishPondIM                          0x00000001009927b8 -[GKPhotoBrowser photoViewDidSelected] + 252
	6   FishPondIM                          0x0000000100997ac0 -[GKPhotoBrowser(Private) browserFirstAppear] + 112
	7   FishPondIM                          0x0000000100999690 __40-[GKPhotoBrowserHandler browserNoneShow]_block_invoke.5 + 96
	8   UIKitCore                           0x00000001d45a6830 __UIVIEW_IS_EXECUTING_ANIMATION_COMPLETION_BLOCK__ + 36
	9   UIKitCore                           0x00000001d36148d8 B3834960-244B-34E4-9EA0-CA4BB44EF0F3 + 846040
	10  UIKitCore                           0x00000001d3613834 B3834960-244B-34E4-9EA0-CA4BB44EF0F3 + 841780
	11  UIKitCore                           0x00000001d3612f50 B3834960-244B-34E4-9EA0-CA4BB44EF0F3 + 839504
	12  QuartzCore                          0x00000001d2a0e624 84CF5508-8323-3958-8144-C5111C822668 + 79396
	13  libdispatch.dylib                   0x00000001d89a6eac BB347F0E-F21C-3607-82E6-C8D750FDBF8C + 16044
	14  libdispatch.dylib                   0x00000001d89b56a4 BB347F0E-F21C-3607-82E6-C8D750FDBF8C + 75428
	15  libdispatch.dylib                   0x00000001d89b52f4 _dispatch_main_queue_callback_4CF + 44
	16  CoreFoundation                      0x00000001d156fc28 4230C122-42E8-383B-BEEC-EE7B61F8BB61 + 625704
	17  CoreFoundation                      0x00000001d1551560 4230C122-42E8-383B-BEEC-EE7B61F8BB61 + 501088
	18  CoreFoundation                      0x00000001d15563ec CFRunLoopRunSpecific + 612
	19  GraphicsServices                    0x000000020ca1b35c GSEventRunModal + 164
	20  UIKitCore                           0x00000001d38e36e8 B3834960-244B-34E4-9EA0-CA4BB44EF0F3 + 3790568
	21  UIKitCore                           0x00000001d38e334c UIApplicationMain + 340
	22  FishPondIM                          0x00000001005513c8 main + 120
	23  dyld                                0x00000001f0a56dec 8A423F3F-B318-315E-99C7-05EE532E9C0D + 89580
)

**Comment by QuintGao** [comment]
<img width="445" alt="image" src="https://github.com/QuintGao/GKPhotoBrowser/assets/13514024/97f5ddf4-222d-489c-a107-857c248e2b92">
看这里是第一次显示的时候越界了，应该是你传入的 index 有问题

**Comment by iPermanent** [comment]
OK，明白了
