### ISSUE TITLE
asset 图片加载问题

### ISSUE THREAD

**Issue by Li-Qun** [QuintGao/GKPhotoBrowser#180]
涉及到icloud 图片  ，如果是 if (photo.imageAsset)  最终直接返回getImage:^(NSData * _Nonnull data, UIImage * _Nonnull image)
,并不能知道这个图片是否是从icloud 获取的，如果失败了，也不能做出因为icloud 失败的提示

于是考虑自定义加载类方案， 但是 GKWebImageCompletionBlock completionBlock = ^(UIImage *image, NSURL *url, BOOL finished, NSError *error)  闭包返回的error 错误原因根本没被使用，也不能正确对加载失败的原因做出提示

因此 期望 加载图片的方法能提供权限 把不能获取图片错误原因抛出去 外部想处理 就可以根据自己的需求 定制错误处理方案:网络错误 提示网络不佳，icloud 图片下载失败 打上icloud 失败的标签（根据这个错误 用户才知道asset 图 为什么不显示）

**Comment by Li-Qun** [comment]
或者说 对于图片的加载回调 结果 提供代理方（从缓存中取也需要执行这个）外边就会知道 啊 图片image 我获取到了（或者失败了）我可以在这个时机做什么bla bla

**Comment by QuintGao** [comment]
看看最新代码是否满足需求
