### ISSUE TITLE
imageAsset 加载问题

### ISSUE THREAD

**Issue by 1knight520** [QuintGao/GKPhotoBrowser#184]
![simulator_screenshot_327EBE9F-A3BD-4024-B476-EB1E73BC0661](https://github.com/QuintGao/GKPhotoBrowser/assets/23653418/6c513cd2-1044-4b9c-b15f-17942412b56e)

NSMutableArray *photos = [NSMutableArray new];

    for (XScannerModel *mm in self.dataAry) {
        GKPhoto *photo = [GKPhoto new];
        if (mm.asset.mediaType == PHAssetMediaTypeImage) {
            photo.imageAsset = mm.asset;
        }else if (mm.asset.mediaType == PHAssetMediaTypeVideo) {
            photo.videoAsset = mm.asset;
//            photo.autoPlay = NO;
        }
     
        [photos addObject:photo];
    }
    
    
    GKPhotoBrowser *browser = [GKPhotoBrowser photoBrowserWithPhotos:photos currentIndex:indexPath.row];
    [browser showFromVC:self];

使用asset方式时，图片显示了，但是却有图片加载失败，是我用错了吗

**Comment by 1knight520** [comment]
GKPhotoBrowser *browser = [GKPhotoBrowser photoBrowserWithPhotos:photos currentIndex:indexPath.row];
    browser.failStyle = GKPhotoBrowserFailStyleCustom;
    [browser showFromVC:self];
    
    我这边加个失败的样式自定义就OK了，但是为啥失败了还能显示相册图片，我就没仔细去看了

**Comment by 1knight520** [comment]
photo.autoPlay = NO;
这个视频开始虽然暂停了，但是点击不会播放
phone x,15.1系统

**Comment by QuintGao** [comment]
> 使用asset方式时，图片显示了，但是却有图片加载失败，是我用错了吗

能提供demo吗

**Comment by 1knight520** [comment]
> 



> > 使用asset方式时，图片显示了，但是却有图片加载失败，是我用错了吗
> 
> 能提供demo吗

你的demo复现出来了，微信朋友圈-发布-选择一张照片-完成-点击那张查看-中间就有“图片加载失败”白色字样
