### ISSUE TITLE
加载本地内存中的图片和视频

### ISSUE THREAD

**Issue by ghost** [QuintGao/GKPhotoBrowser#187]
Task <011C6288-2B39-46D8-BF56-FA5F1514A660>.<1> finished with error [-1002] Error Domain=NSURLErrorDomain Code=-1002 "不支持的URL" UserInfo={NSLocalizedDescription=不支持的URL, NSErrorFailingURLStringKey=/var/mobile/Containers/Data/Application/977822F7-2F63-4DD7-9821-5D18BEE4542F/Documents/ConversationResource/0/0/7dhqmws2k/image/img1695520300118.jpg, NSErrorFailingURLKey=/var/mobile/Containers/Data/Application/977822F7-2F63-4DD7-9821-5D18BEE4542F/Documents/ConversationResource/0/0/7dhqmws2k/image/img1695520300118.jpg,

**Comment by QuintGao** [comment]
咋用的？
