### ISSUE TITLE
这个库限制了SDWebImage的版本吧？

### ISSUE THREAD

**Issue by sec7et** [QuintGao/GKPhotoBrowser#19]
作者你好，我项目中的SD版本是pod 'SDWebImage', '~> 4.4.1'，手动导入你的库。
似乎pod上面你的库是1.2.8版本，最新这边是1.3.4？
然后在GKPhotoView.m中，- (void)loadImageWithPhoto:(GKPhoto *)photo   这个方法下面
NSData *imageData = [[SDImageCache sharedImageCache]  diskImageDataForKey:photo.url.absoluteString];
[strongSelf setupPhotoWithData:imageData image:image];
也就是186行左右，默认会报错，因为SDW里面找不到这个方法了。
作者是否可以尝试一下？4.4.1的SDW是我这边pod里搜到最新的了。

**Comment by QuintGao** [comment]
你好，这个库需要SDWebImage最低版本为4.4.2，如何搜不到可以使用pod setup或pod update更新本地仓库。

**Comment by sec7et** [comment]
好的。没想到更新的这么快，回头我更新一下。谢谢了
