### ISSUE TITLE
建议微信聊天图片视频浏览支持一下本地路径的图片与视频资源(发送方一般会用到)

### ISSUE THREAD

**Issue by jozdee** [QuintGao/GKPhotoBrowser#191]
- (void)showBrowserWithIndex:(NSInteger)index {
    NSMutableArray *photos = [NSMutableArray new];
    [self.dataSource enumerateObjectsUsingBlock:^(GKTimeLineModel *model, NSUInteger idx, BOOL * _Nonnull stop) {
        GKChatViewCell *cell = [self.tableView cellForRowAtIndexPath:[NSIndexPath indexPathForRow:idx inSection:0]];
        GKTimeLineImage *img = model.images.firstObject;
        
        GKPhoto *photo = [GKPhoto new];
        photo.url = [NSURL URLWithString:img.url];
        photo.sourceImageView = cell.imgView;
        if (img.isVideo) {
            photo.videoUrl = [NSURL URLWithString:img.video_url];
            photo.autoPlay = NO;
        }
        
        // 首次点击的是视频，自动播放
        if (img.isVideo && index == idx) {
            photo.isVideoClicked = YES;
        }
        
        [photos addObject:photo];
    }];
    
    GKPhotoBrowser *browser = [GKPhotoBrowser photoBrowserWithPhotos:photos currentIndex:index];
    browser.showStyle = GKPhotoBrowserShowStyleZoom;
    browser.hideStyle = GKPhotoBrowserHideStyleZoomScale;
    browser.hidesPageControl = YES;
    browser.hidesSavedBtn = YES;
    browser.hidesCountLabel = YES;
    browser.delegate = self;
    browser.isSingleTapDisabled = YES;
    browser.isVideoPausedWhenDragged = NO;
    [browser setupVideoProgressProtocol:[GKVideoProgressView new]];
    browser.isVideoReplay = NO;
    [browser showFromVC:self];
}

#pragma mark - GKPhotoBrowserDelegate
- (void)photoBrowser:(GKPhotoBrowser *)browser singleTapWithIndex:(NSInteger)index {
    GKPhoto *photo = browser.curPhoto;
    if (photo.isVideo) {
        browser.progressView.hidden = !browser.progressView.isHidden;
    }else {
        [browser dismiss];
    }
}

**Comment by QuintGao** [comment]
已添加

**Comment by jozdee** [comment]
没有支持沙盒本地路径的图片浏览
