### ISSUE TITLE
2.7.3升级3.0.3后报错：Duplicate interface definition for class 'GKPhotoBrowser'

### ISSUE THREAD

**Issue by ipad4** [QuintGao/GKPhotoBrowser#196]
2.7.3升级3.0.3后报错：Duplicate interface definition for class 'GKPhotoBrowser'
pod 'GKPhotoBrowser/Core' , '3.0.3'
pod 'GKPhotoBrowser/SD' , '3.0.3'

**Comment by QuintGao** [comment]
没复现，看着应该是重复引入导致的
