### ISSUE TITLE
更新至 3.1.0 后，layoutBlock 内无法获取 safeAreaInsets.top 和 statusBar Height 了

### ISSUE THREAD

**Issue by LisonFan** [QuintGao/GKPhotoBrowser#197]
@QuintGao 
![Xcode 2024-09-09 17 34 45](https://github.com/user-attachments/assets/f792665c-fbf0-4515-bf5a-3009a2b22688)

**Comment by QuintGao** [comment]
怎么配置的，我这边试了能获取的

**Comment by QuintGao** [comment]
最新版已修复
