### ISSUE TITLE
图片浏览器消失时，消失动画能否定位至当前的图片

### ISSUE THREAD

**Issue by Plotac** [QuintGao/GKPhotoBrowser#199]
ABCD四张图片，点击A图，展示brower，滚动至D图，点击图片使brower消失，此时brower消失动画依然定位至A图的位置，能否定位到当前图片（也就是D图）的位置

**Comment by QuintGao** [comment]
这个是支持的，你应该是sourceImageView传错了，应该传对应位置的sourceImageView

**Comment by Plotac** [comment]
> 这个是支持的，你应该是sourceImageView传错了，应该传对应位置的sourceImageView

感谢回复。今天看了下代码，确实设置的有问题~
