### ISSUE TITLE
首次显示的时候 滑动图片卡顿

### ISSUE THREAD

**Issue by lsmakethebest** [QuintGao/GKPhotoBrowser#20]
首次显示的时候，滑动图片卡顿，当所有的图片都看过之后，在滑动就不卡顿了

**Comment by QuintGao** [comment]
我这里没有出现卡顿的情况，能否提供demo我测试一下。另外中间那个黑圈应该是loadingView没隐藏导致的，我处理一下。

**Comment by lsmakethebest** [comment]
![1535016083969](https://user-images.githubusercontent.com/13564467/44517227-ae87c100-a6f9-11e8-8f41-4695a043b1b8.jpg)

**Comment by QuintGao** [comment]
#19 最低支持的SD版本是4.4.2

**Comment by lsmakethebest** [comment]
我把sdwebimage移除掉，再重新pod install下，滑动不卡顿了

**Comment by QuintGao** [comment]
嗯 确实有这个问题，我修复一下。

**Comment by QuintGao** [comment]
该问题已修复，请更新到最新版本使用。

**Comment by lsmakethebest** [comment]
ok




在2018年08月24日 15:06，QuintGao 写道：

该问题已修复，请更新到最新版本使用。

**Comment by lsmakethebest** [comment]
每次重新开启app打开相同图片，滑动还是会卡顿，隐藏在查看图片滑动不卡顿，demo也是一样
修改了下面的代码，其他地方没有动
还有个小情况，controller的 self.view.backgroundColor可否弄成可配置的，我们的奇葩设计非要弄成其他透明的颜色
`
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    GKTimeLineViewCell *cell = [tableView dequeueReusableCellWithIdentifier:kTimeLineViewCellID forIndexPath:indexPath];
    
    cell.timeLineFrame = self.dataFrames[indexPath.row];
    
    cell.photosImgClickBlock = ^(GKTimeLineViewCell *cell, NSInteger index) {
        NSMutableArray *photos = [NSMutableArray new];
        
        NSArray *a=@[@"https://togo-public-test.oss-cn-beijing.aliyuncs.com/c2869474249c457e9efa2d6da147da64",@"https://togo-public-test.oss-cn-beijing.aliyuncs.com/5211f64a36c449e989b24ed5763ee8ec",@"https://togo-public-test.oss-cn-beijing.aliyuncs.com/1c17b792de1b49abb548cdcbcd092555"];
        [a enumerateObjectsUsingBlock:^(NSString * _Nonnull obj, NSUInteger idx, BOOL * _Nonnull stop) {
            
            GKPhoto *photo = [GKPhoto new];
            photo.url = [NSURL URLWithString:obj];
            
//            photo.sourceImageView = cell.photosView.subviews[idx];
            
            [photos addObject:photo];
        }];
        
        self.pageControl = [[UIPageControl alloc] init];
        self.pageControl.numberOfPages = photos.count;
        self.pageControl.currentPage = index;
        self.pageControl.hidesForSinglePage = YES;
        
        GKPhotoBrowser *browser = [GKPhotoBrowser photoBrowserWithPhotos:photos currentIndex:index];
        browser.showStyle = GKPhotoBrowserShowStyleNone;        // 缩放显示
        browser.hideStyle = GKPhotoBrowserHideStyleZoomScale;   // 缩放隐藏
        browser.loadStyle = GKPhotoBrowserLoadStyleIndeterminateMask; // 不明确的加载方式带阴影
//        browser.isStatusBarShow     = YES;
//        browser.isResumePhotoZoom   = YES;
        [browser setupCoverViews:@[self.pageControl] layoutBlock:^(GKPhotoBrowser *photoBrowser, CGRect superFrame) {
            
            CGFloat pointY = 0;
            if (photoBrowser.isLandspace) {
                pointY = superFrame.size.height - 20;
            }else {
                pointY = superFrame.size.height - 10;
            }
            
            self.pageControl.center = CGPointMake(superFrame.size.width * 0.5, pointY);
            
//            self.count ++;
        }];
        
        browser.delegate = self;
        
        [browser showFromVC:self];
        
        self.browser = browser;
    };
    
    return cell;
}
`

**Comment by lsmakethebest** [comment]
`
每次重新开启app打开相同图片，滑动还是会卡顿，隐藏在查看图片滑动不卡顿，demo也是一样
修改了下面的代码，其他地方没有动
还有个小情况，controller的 self.view.backgroundColor可否弄成可配置的，我们的奇葩设计非要弄成其他透明的颜色
(UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
GKTimeLineViewCell *cell = [tableView dequeueReusableCellWithIdentifier:kTimeLineViewCellID forIndexPath:indexPath];

cell.timeLineFrame = self.dataFrames[indexPath.row];

cell.photosImgClickBlock = ^(GKTimeLineViewCell *cell, NSInteger index) {
NSMutableArray *photos = [NSMutableArray new];

  NSArray *a=@[@"https://togo-public-test.oss-cn-beijing.aliyuncs.com/c2869474249c457e9efa2d6da147da64",@"https://togo-public-test.oss-cn-beijing.aliyuncs.com/5211f64a36c449e989b24ed5763ee8ec",@"https://togo-public-test.oss-cn-beijing.aliyuncs.com/1c17b792de1b49abb548cdcbcd092555"];
  [a enumerateObjectsUsingBlock:^(NSString * _Nonnull obj, NSUInteger idx, BOOL * _Nonnull stop) {
      
      GKPhoto *photo = [GKPhoto new];
      photo.url = [NSURL URLWithString:obj];
// photo.sourceImageView = cell.photosView.subviews[idx];

        [photos addObject:photo];
    }];
    
    self.pageControl = [[UIPageControl alloc] init];
    self.pageControl.numberOfPages = photos.count;
    self.pageControl.currentPage = index;
    self.pageControl.hidesForSinglePage = YES;
    
    GKPhotoBrowser *browser = [GKPhotoBrowser photoBrowserWithPhotos:photos currentIndex:index];
    browser.showStyle = GKPhotoBrowserShowStyleNone;        // 缩放显示
    browser.hideStyle = GKPhotoBrowserHideStyleZoomScale;   // 缩放隐藏
    browser.loadStyle = GKPhotoBrowserLoadStyleIndeterminateMask; // 不明确的加载方式带阴影
// browser.isStatusBarShow = YES;
// browser.isResumePhotoZoom = YES;
[browser setupCoverViews:@[self.pageControl] layoutBlock:^(GKPhotoBrowser *photoBrowser, CGRect superFrame) {

        CGFloat pointY = 0;
        if (photoBrowser.isLandspace) {
            pointY = superFrame.size.height - 20;
        }else {
            pointY = superFrame.size.height - 10;
        }
        
        self.pageControl.center = CGPointMake(superFrame.size.width * 0.5, pointY);
// self.count ++;
}];

    browser.delegate = self;
    
    [browser showFromVC:self];
    
    self.browser = browser;
};

return cell;
}
`

**Comment by QuintGao** [comment]
你好，第一次显示的时候确实有卡顿问题，目前还没有找到原因，另外你说的设置背景颜色功能已添加。

**Comment by lsmakethebest** [comment]
好的 谢谢
