### ISSUE TITLE
removePhotoAtIndex功能不完善

### ISSUE THREAD

**Issue by GitHubSiegeLion** [QuintGao/GKPhotoBrowser#22]
用此方法删除指定索引的图片，会出现已删除图片和新的该位置上的图片叠加（图片大小不一时一眼就能看到，大小一样是可以通过视图调试看到），而且已删除图片仍然占着位置（浏览器末尾有黑色页，删除几张就有几页）。我在resetPhotoBrowserWithPhotos方法中增加了将self.reusablePhotoViews和self.visiblePhotoViews中的[view removeFromSuperview]，并在[self setupPhotoViews]后调用[self layoutSubviews]，才规避。希望作者能有更好的解决方法处理此问题。

**Comment by QuintGao** [comment]
你好，该问题已修复，请下载最新版本使用。

**Comment by GitHubSiegeLion** [comment]
恩，可以了，多谢。
