### ISSUE TITLE
手势冲突

### ISSUE THREAD

**Issue by iwantFB** [QuintGao/GKPhotoBrowser#24]
集成之后，tableView的下拉就会失效，拉不动
你这样写category操作系统级别的api，很容易出问题啊

**Comment by QuintGao** [comment]
你用的是最新版本吗，以前已经修复过这个问题。

**Comment by iwantFB** [comment]
直接pod 安装的

**Comment by QuintGao** [comment]
以前有个方法影响滑动，已经改成UIScrollview的子类了，现在分类里面的方法应该不会影响滑动，你再看看你pod的版本是最新版1.3.7吗

**Comment by iwantFB** [comment]
的确是最新版本，是需要在界面做单独的设置么

**Comment by QuintGao** [comment]
#18 下拉卡顿问题以前就解决过，现在的UIScrollView的分类不会对下拉有影响。你看看是不是你项目中有其他库导致的不能下拉。
