### ISSUE TITLE
 解决全屏滑动会导致不能直接下拉scrollview

### ISSUE THREAD

**Issue by eric1202** [QuintGao/GKPhotoBrowser#25]
UIScrollView+GKGestureHandle.m

第 24行 #pragma mark - 解决全屏滑动
- (BOOL)gestureRecognizerShouldBegin:(UIGestureRecognizer *)gestureRecognizer {
、、、、
}
这个方法会导致其他的scrollview 在原始offset的时候不能下拉 
要往上拉一点才能下拉
改为 return YES 就ok

请问

> `isScrollViewOnTopOrBottom` 为何要返回NO

**Comment by QuintGao** [comment]
#18 这个问题已经修复过了，请更新到最新版使用，isScrollViewOnTopOrBottom 这个方法在最新版是在UIScrollView的子类中实现的，不会影响其他UIScrollView的滑动。

**Comment by eric1202** [comment]
恩 之前的是1.3.4
