### ISSUE TITLE
当把gif只缓存到内存中，点击gif图片的问题。

### ISSUE THREAD

**Issue by kakashilw** [QuintGao/GKPhotoBrowser#27]
你好，首先感谢提供这么好用的图片浏览库。

不过我们在使用的时候遇到了一共问题，就是因为gif图片都比较大，所以我们从网络获取到gif，然后加载之后，不把他存到本地，而是只放到内存了，用到了SDWebImage的这个属性SDWebImageCacheMemoryOnly。

然后配合这个库的话，就会发现当第一次的时候点击gif是会动的，而关闭再打开就静止了，不知这个库对于这种情况有什么解决办法吗？

**Comment by QuintGao** [comment]
目前没遇到过这种情况，你那边能提供demo吗

**Comment by kakashilw** [comment]
你好，只需要把GKWebImageManager.m的24行的SDWebImageRetryFailed改为SDWebImageCacheMemoryOnly，然后运行demo，然后点击“GIF图片”那一行的demo，进去点击gif图片，就会发现第一次点击gif是动的，然后再点击就静止了。我这边刚刚测试过。。

**Comment by QuintGao** [comment]
如果想要正常播放gif，可以把isLowGifMemory设置为YES，这个播放gif效率更好
