### ISSUE TITLE
- (void)setupPhoto:(GKPhoto *)photo

### ISSUE THREAD

**Issue by huipengo** [QuintGao/GKPhotoBrowser#28]
- (void)setupPhoto:(GKPhoto *)photo 方法会执行两次

    - (void)viewWillAppear:(BOOL)animated {
        [super viewWillAppear:animated];
    
        GKPhoto *photo          = [self currentPhoto];
        GKPhotoView *photoView  = [self currentPhotoView];
    
        if ([_imageProtocol imageFromMemoryForURL:photo.url] || photo.image) {
            [photoView setupPhoto:photo];
        }else {
            photoView.imageView.image = photo.placeholderImage ? photo.placeholderImage : 
    photo.sourceImageView.image;
            [photoView adjustFrame];
        }
    
        switch (self.showStyle) {
            case GKPhotoBrowserShowStyleNone:
                [self browserNoneShow];
                break;
            case GKPhotoBrowserShowStylePush:
                [self browserPushShow];
               break;
            case GKPhotoBrowserShowStyleZoom:{
                [self browserZoomShow];
            }
                break;
            
            default:
                break;
        }
    }

    这个里面会走两次

**Comment by huipengo** [comment]
- (void)loadImageWithPhoto:(GKPhoto *)photo {
            [self.imageView removeFromSuperview];
            self.imageView = nil;
            [self.scrollView addSubview:self.imageView];
    }

这句移出又添加干嘛的呢？

**Comment by QuintGao** [comment]
防止在切换图片的时候，出现图片的重叠
