### ISSUE TITLE
UIScrollView+GKGestureHandle 影响其他

### ISSUE THREAD

**Issue by Mamakou** [QuintGao/GKPhotoBrowser#29]
楼主，你的那个UIScrollView+GKGestureHandle建议不要添加，会影响app，导致滑不动

**Comment by QuintGao** [comment]
你用的是最新版本的吗，版本号是多少？

**Comment by Mamakou** [comment]
> 你用的是最新版本的吗，版本号是多少？

应该是你这个上一版的，这一版我还没用，上一版的我直接将这个文件给删掉了，因为确实会影响本程序，这次特来反馈一下

**Comment by QuintGao** [comment]
嗯 这个问题之前有人提了，已经修复过了。
