### ISSUE TITLE
GKPhotoBrowser添加其他视图手势发生冲突

### ISSUE THREAD

**Issue by 200895045** [QuintGao/GKPhotoBrowser#3]
执行下面代码添加view，如view中添加scrollView、button等控件，操作时会发生手势冲突
```
[browser setupCoverViews:@[view] layoutBlock:^(GKPhotoBrowser *photoBrowser, CGRect superFrame) {
    [self resetCoverFrame:superFrame index:photoBrowser.currentIndex];
}];
```

**Comment by 200895045** [comment]
这个问题可以解决吗？

**Comment by QuintGao** [comment]
有Demo吗，发邮箱1094887059@qq.com，我抽时间看看。

**Comment by 200895045** [comment]
集成到项目中的，不好拆分。
1、应该就是你将 GKPhotoBrowser 中这个平移手势添加到了当前view中引起的：
'''
@property (nonatomic, strong) UIPanGestureRecognizer *panGesture;
'''
2、再通过这个方法添加其他子控件，如果这些控件中有touch事件等就会造成冲突了
'''
[browser setupCoverViews:@[view1, view2] layoutBlock:^(GKPhotoBrowser *photoBrowser, CGRect superFrame) {
    [self resetCoverFrame:superFrame index:browser.currentIndex];
}];
'''

**Comment by 200895045** [comment]
集成到项目中的，不好拆分。
1、应该就是你将 GKPhotoBrowser 中这个平移手势添加到了当前view中引起的：
```
@property (nonatomic, strong) UIPanGestureRecognizer *panGesture;
```
2、再通过这个方法添加的子控件也是加入了view中，如果这些控件中有touch事件等就会造成冲突了
```
[browser setupCoverViews:@[view1, view2] layoutBlock:^(GKPhotoBrowser *photoBrowser, CGRect superFrame) {
[self resetCoverFrame:superFrame index:browser.currentIndex];
}];
```
