### ISSUE TITLE
zoom 之后恢复原图大小，无法上滑/下滑 淡出

### ISSUE THREAD

**Issue by quanh** [QuintGao/GKPhotoBrowser#31]
我在使用本库时发现支持上下滑动淡出视图的功能会在zoom之后失效，通过修改源码修复了此问题， 在您的demo “tableviewcell多图zoom” 进行如下操作：即可复现

1. 点击开大图
2. zoom 放大图片
3. zoom 恢复原图
4. 上滑/下滑 尝试淡出视图

**Comment by QuintGao** [comment]
我这个库在zoom放大状态下是不支持滑动隐藏的，出现该问题应该是zoom恢复原图操作时，其实并没有恢复到原图，还是在zoom放大状态，你可以多试几次，看看是不是我说的这个情况

**Comment by quanh** [comment]
zoom 放大， 然后zoom缩小后会自动恢复大小， 自动恢复之后的BUG, 我尝试多次，每次都会出现

**Comment by quanh** [comment]
我使用的是 2018.11.9 的旧版本， 然后在仓库拉取的最新版本的demo中也复现了

**Comment by quanh** [comment]
对了， 我忘了， 这个情况是在X 系列复现的。 我刚才测试了一下， 非X系列没有这个问题

**Comment by QuintGao** [comment]
x系列我在模拟器上试了，没问题，你那边如果有真机可以帮忙看看问题出在哪

**Comment by quanh** [comment]
在xsMax 的机器和模拟器， 我观察到 `GKPhotoBrowser.m`  509 行：
```
UIDeviceOrientation orientation = [UIDevice currentDevice].orientation;
```

会出现 `UIDeviceOrientationUnknow` 这种类型, 同时 `self.isPortraitToUp 为 NO`, 
实际上设备是`Portrait (bottom home button)`。

但是我在XR/ XS 和X 上 并没有发现此问题， 
另外我观察到， 第一次xsMax 获取到总是`UIDeviceOrientationUnknow `, 通过重新获取即可修正此问题， 所以我在 上面提到的509行之前添加了重新获取设备方向的调用， 解决了此问题。

你可以在模拟器 xsMax 上尝试复现此问题。
