### ISSUE TITLE
是否支持自定义“图片加载失败，请检查网络后重试”？

### ISSUE THREAD

**Issue by xusion** [QuintGao/GKPhotoBrowser#41]
是否支持自定义“图片加载失败，请检查网络后重试”？
在图片加载失败后，这句话能不能自定义，或者使用一张“裂图”来显示。

这个问题是图片失败，但提示检查网络后重试，于理不通。

**Comment by QuintGao** [comment]
你好，增加了GKPhotoBrowserFailStyle，可自定义加载失败的显示方式

**Comment by xusion** [comment]
我更新来试试，谢谢
