### ISSUE TITLE
CALayer position contains NaN: [nan nan]

### ISSUE THREAD

**Issue by lilong7676** [QuintGao/GKPhotoBrowser#43]
0 CoreFoundation | ___exceptionPreprocess + 228
-- | --
1 libobjc.A.dylib | objc_exception_throw + 56
2 CoreFoundation | -[NSCache init]
3 QuartzCore | 0x00000001a5615000 + 1354148
4 QuartzCore | 0x00000001a5615000 + 1290436
5 QuartzCore | 0x00000001a5615000 + 1292332
6 UIKitCore | -[UIView(Geometry) setFrame:] + 356
7 UIKitCore | -[UIImageView _setViewGeometry:forMetric:] + 172
8 ManagePlus | 0x0000000102d18000 + 9189636
9 ManagePlus | 0x0000000102d18000 + 9188608
10 UIKitCore | -[UIGestureRecognizerTarget _sendActionWithGestureRecognizer:] + 64
11 UIKitCore | __UIGestureRecognizerSendTargetActions + 124
12 UIKitCore | __UIGestureRecognizerSendActions + 320
13 UIKitCore | -[UIGestureRecognizer _updateGestureWithEvent:buttonEvent:] + 764
14 UIKitCore | __UIGestureEnvironmentUpdate + 1096
15 UIKitCore | -[UIGestureEnvironment _deliverEvent:toGestureRecognizers:usingBlock:] + 384
16 UIKitCore | -[UIGestureEnvironment _updateForEvent:window:] + 204
17 UIKitCore | -[UIWindow sendEvent:] + 3128
18 UIKitCore | -[UIApplication sendEvent:] + 340
19 UIKitCore | ___dispatchPreprocessedEventFromEventQueue + 1620
20 UIKitCore | ___handleEventQueueInternal + 4740
21 UIKitCore | ___handleHIDEventFetcherDrain + 152
22 CoreFoundation | ___CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
23 CoreFoundation | ___CFRunLoopDoSource0 + 88
24 CoreFoundation | ___CFRunLoopDoSources0 + 176
25 CoreFoundation | ___CFRunLoopRun + 1040
26 CoreFoundation | CFRunLoopRunSpecific + 436
27 GraphicsServices | GSEventRunModal + 100
28 UIKitCore | UIApplicationMain + 212
29 ManagePlus | 0x0000000102d18000 + 9485528
30 libdyld.dylib | 0x00000001a0ba2000 + 2996

**Comment by lilong7676** [comment]
[ GKPhotoBrowser ] WillAppear 时发生，偶发现象。

**Comment by QuintGao** [comment]
问题已修复

**Comment by lilong7676** [comment]
0 CoreFoundation | ___exceptionPreprocess + 228
-- | --
1 libobjc.A.dylib | objc_exception_throw + 56
2 CoreFoundation | -[NSCache init]
3 QuartzCore | 0x00000001e4a71000 + 1339284
4 QuartzCore | 0x00000001e4a71000 + 1275912
5 QuartzCore | 0x00000001e4a71000 + 1277788
6 UIKitCore | -[UIView(Geometry) setFrame:] + 356
7 UIKitCore | -[UIImageView _setViewGeometry:forMetric:] + 172
8 ManagePlus | 0x0000000104e24000 + 9198588
9 ManagePlus | 0x0000000104e24000 + 9197508
10 UIKitCore | -[UIGestureRecognizerTarget _sendActionWithGestureRecognizer:] + 64
11 UIKitCore | __UIGestureRecognizerSendTargetActions + 124
12 UIKitCore | __UIGestureRecognizerSendActions + 316
13 UIKitCore | -[UIGestureRecognizer _updateGestureWithEvent:buttonEvent:] + 760
14 UIKitCore | __UIGestureEnvironmentUpdate + 2180
15 UIKitCore | -[UIGestureEnvironment _deliverEvent:toGestureRecognizers:usingBlock:] + 384
16 UIKitCore | -[UIGestureEnvironment _updateForEvent:window:] + 204
17 UIKitCore | -[UIWindow sendEvent:] + 3112
18 UIKitCore | -[UIApplication sendEvent:] + 340
19 UIKitCore | ___dispatchPreprocessedEventFromEventQueue + 1768
20 UIKitCore | ___handleEventQueueInternal + 4828
21 UIKitCore | ___handleHIDEventFetcherDrain + 152
22 CoreFoundation | ___CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
23 CoreFoundation | ___CFRunLoopDoSource0 + 88
24 CoreFoundation | ___CFRunLoopDoSources0 + 176
25 CoreFoundation | ___CFRunLoopRun + 1004
26 CoreFoundation | CFRunLoopRunSpecific + 436
27 GraphicsServices | GSEventRunModal + 104
28 UIKitCore | UIApplicationMain + 212
29 ManagePlus | 0x0000000104e24000 + 9497556
30 libdyld.dylib | 0x00000001e0171000 + 6368

**Comment by lilong7676** [comment]
CALayerInvalidGeometry
CALayer position contains NaN: [nan nan]

又出现了这个问题😆

**Comment by QuintGao** [comment]
具体怎么出现的？

**Comment by lilong7676** [comment]
我是没有复现。。好像是图片预览时，手指缩放引起的

**Comment by QuintGao** [comment]
你那边有没有传sourceFrame，其中有width或height为0的情况

**Comment by lilong7676** [comment]
没有传sourceFrame。

**Comment by QuintGao** [comment]
你再试下最新版，看看还会不会出现

**Comment by lilong7676** [comment]
好的，我更新下

**Comment by lilong7676** [comment]
CoreFoundation | ___exceptionPreprocess + 228
-- | --
1 libobjc.A.dylib | objc_exception_throw + 56
2 CoreFoundation | -[NSCache init]
3 QuartzCore | 0x0000000212c6d000 + 1337404
4 QuartzCore | 0x0000000212c6d000 + 1273732
5 QuartzCore | 0x0000000212c6d000 + 1275628
6 UIKitCore | -[UIView(Geometry) setFrame:] + 356
7 UIKitCore | -[UIImageView _setViewGeometry:forMetric:] + 172
8 ManagePlus | -[GKPhotoBrowser handlePanZoomScale:] (GKPhotoBrowser.m:707)
9 ManagePlus | -[GKPhotoBrowser handlePanGesture:] (GKPhotoBrowser.m:675)
10 UIKitCore | -[UIGestureRecognizerTarget _sendActionWithGestureRecognizer:] + 64
11 UIKitCore | __UIGestureRecognizerSendTargetActions + 124
12 UIKitCore | __UIGestureRecognizerSendActions + 320
13 UIKitCore | -[UIGestureRecognizer _updateGestureWithEvent:buttonEvent:] + 764
14 UIKitCore | __UIGestureEnvironmentUpdate + 1096
15 UIKitCore | -[UIGestureEnvironment _deliverEvent:toGestureRecognizers:usingBlock:] + 384
16 UIKitCore | -[UIGestureEnvironment _updateForEvent:window:] + 204
17 UIKitCore | -[UIWindow sendEvent:] + 3128
18 UIKitCore | -[UIApplication sendEvent:] + 340
19 UIKitCore | ___dispatchPreprocessedEventFromEventQueue + 1440
20 UIKitCore | ___handleEventQueueInternal + 4740
21 UIKitCore | ___handleHIDEventFetcherDrain + 152
22 CoreFoundation | ___CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
23 CoreFoundation | ___CFRunLoopDoSource0 + 88
24 CoreFoundation | ___CFRunLoopDoSources0 + 176
25 CoreFoundation | ___CFRunLoopRun + 1040
26 CoreFoundation | CFRunLoopRunSpecific + 436
27 GraphicsServices | GSEventRunModal + 100
28 UIKitCore | UIApplicationMain + 212
29 ManagePlus | main (main.mm:0)
30 libdyld.dylib | 0x000000020e210000 + 2964

**Comment by lilong7676** [comment]
8 ManagePlus | -[GKPhotoBrowser handlePanZoomScale:] (GKPhotoBrowser.m:707)
-- | --
9 ManagePlus | -[GKPhotoBrowser handlePanGesture:] (GKPhotoBrowser.m:675)

**Comment by lilong7676** [comment]
-[GKPhotoBrowser handlePanZoomScale:] (GKPhotoBrowser.m:707)
--

看下这个方法里是不是有除0的操作？

**Comment by lilong7676** [comment]
额 我看到你更新代码了，我更新下再看下。

**Comment by QuintGao** [comment]
还会出现这种情况？

**Comment by lilong7676** [comment]
还在观察。

**Comment by HelloHchen** [comment]
![企业微信截图_cb2155b8-6404-446e-9a85-bb7ed91dc3e2](https://user-images.githubusercontent.com/38774301/178087889-621e4bde-cade-4b70-b328-497cf2b43b0e.JPG)

遇到+1
现在只能这样先处理下，看imageF的height为nan，感觉像SD图片没加载出来，没拿到size，导致height为0，然后又除以0，导致nan，毕竟分母不能为0

**Comment by HelloHchen** [comment]
个人感觉处理的不对，不应该放在这里，先随便搞一下
