### ISSUE TITLE
zoom之后恢复原图大小，无法上滑/下滑淡出 ＃31 这个问题又出现了

### ISSUE THREAD

**Issue by chuansuozhongdelang** [QuintGao/GKPhotoBrowser#44]
zoom之后恢复原图大小，无法上滑/下滑淡出 ＃31 这个问题我机子又出现了，GKPhotoBrowser版本1.4.8，我机子 xs 12.2

**Comment by QuintGao** [comment]
![image](https://user-images.githubusercontent.com/13514024/56112178-d7144200-5f8c-11e9-9388-674dd4ccc35e.png)
你把这里改一下，加入红框里的代码，看看能不能解决，如果可以我就更新下。

**Comment by chuansuozhongdelang** [comment]
如果只是放大一点点就可以，但是放大很多，然后缩小回去，不行的还是不能上下滑动退出

**Comment by chuansuozhongdelang** [comment]
我打了一下断点放大缩小不触发deviceOrientationDidChange方法，第一次进去是UIDeviceOrientationPortrait的，后面某个地方改了

**Comment by QuintGao** [comment]
你确认放大后恢复到原图大小了？放大缩小跟设备方向旋转没关肯定不会触发。

**Comment by chuansuozhongdelang** [comment]
到了的，有震动的

**Comment by QuintGao** [comment]
那不应该，我这里没问题的。能具体说下操作流程或者录个屏吗

**Comment by chuansuozhongdelang** [comment]
[WeChatSight12.mp4.zip](https://github.com/QuintGao/GKPhotoBrowser/files/3078900/WeChatSight12.mp4.zip)
放大到震动一下，然后缩小回去

**Comment by chuansuozhongdelang** [comment]
GKPhoto *photo = [GKPhoto new];
    photo.url = [NSURL URLWithString:@"http://pic.netbian.com/uploads/allimg/180315/110404-152108304476cb.jpg"];
    GKPhotoBrowser *browser = [GKPhotoBrowser photoBrowserWithPhotos:@[photo] currentIndex:0];
    browser.showStyle    = GKPhotoBrowserShowStyleZoom;
    browser.hideStyle    = GKPhotoBrowserHideStyleZoomSlide;
    browser.loadStyle = GKPhotoBrowserHideStyleZoomScale;
    browser.isLowGifMemory = true;
    [browser showFromVC:self];
这是使用代码

**Comment by QuintGao** [comment]
![image](https://user-images.githubusercontent.com/13514024/56115809-e26c6b00-5f96-11e9-82e5-37c5826dc245.png)
再这里也加上UIDeviceOrientationUnknown的判断试试，我测试的是这里有可能会出现UIDeviceOrientationUnknown，具体不知道为什么

**Comment by chuansuozhongdelang** [comment]
我新建了个demo可以的，估计是我用了QMUIKit做底层框架的原因，我自己想办法解决了，谢谢了
