### ISSUE TITLE
最新版本内存泄漏

### ISSUE THREAD

**Issue by LinYYY** [QuintGao/GKPhotoBrowser#49]
GKPhotoBrowser (1.5.1)
GKPhotoBrowser.m的setupPhotoViews方法中 在block中使用了self，循环引用内存泄漏了

![image](https://user-images.githubusercontent.com/12007022/58622120-7b640500-82fd-11e9-8a87-113c10920708.png)

**Comment by QuintGao** [comment]
多谢提醒，问题已修复
