### ISSUE TITLE
关于showStyle的问题

### ISSUE THREAD

**Issue by ChandHsu** [QuintGao/GKPhotoBrowser#5]
GKPhotoBrowserShowStyleZoom这个方式,我发现每次show的时候.photo.imageView的frame都是从CGRectZero开始的,但是打印却是我们想要的结果,是sourceFrame,我用慢放验证了,确实是从最小开始变大的,而不是sourceImageView的位置和大小,请教是什么问题呢?
另外,建议增加一行代码:
    photoView.imageView.contentMode = photo.sourceImageView.contentMode;
这样在隐藏的最后一刻不会因为原图设置的Fill的模式造成闪动,影响效果

**Comment by ChandHsu** [comment]
问题截图:
![image](https://user-images.githubusercontent.com/10771362/37947764-593f3e6c-31bf-11e8-9230-68d6985495e1.png)

**Comment by QuintGao** [comment]
问题已修复

**Comment by ChandHsu** [comment]
好的,有劳大神
