### ISSUE TITLE
双指缩放后，在恢复正常尺寸后，无法通过拖动图片收回图片浏览器页面

### ISSUE THREAD

**Issue by cao903775389** [QuintGao/GKPhotoBrowser#52]
第一次打开是可以通过收回正常隐藏Controller的，缩放后无法收回，只能通过点击收回

**Comment by cao903775389** [comment]
第一次打开是可以通过收回正常隐藏Controller的，缩放后无法收回，只能通过点击收回

**Comment by QuintGao** [comment]
是用的最新版本的吗？1.5.2

**Comment by cao903775389** [comment]
> 是用的最新版本的吗？1.5.2

是的，最新版本

**Comment by QuintGao** [comment]
我demo中有这个问题吗，我这里没有fu'x

**Comment by cao903775389** [comment]
刚才试了下把这个换成了Demo里的 browser.loadStyle = GKPhotoBrowserLoadStyleDeterminate 就可以了，我之前设置的是browser.loadStyle = GKPhotoBrowserLoadStyleIndeterminateMask

**Comment by cao903775389** [comment]
> 我demo中有这个问题吗，我这里没有复现

双击缩放貌似没问题，不过如果设置了loadStyle = GKPhotoBrowserLoadStyleIndeterminateMask，然后双指缩放后 就没发滑动消失了

**Comment by cao903775389** [comment]
> 我demo中有这个问题吗，我这里没有复现

browser.hideStyle = GKPhotoBrowserHideStyleZoomScale

**Comment by QuintGao** [comment]
我设置loadStyle = GKPhotoBrowserLoadStyleIndeterminateMask还是没复现，你是不是没有缩小到正常尺寸

**Comment by cao903775389** [comment]
> 我设置loadStyle = GKPhotoBrowserLoadStyleIndeterminateMask还是没复现，你是不是没有缩小到正常尺寸

**Comment by cao903775389** [comment]
> 我设置loadStyle = GKPhotoBrowserLoadStyleIndeterminateMask还是没复现，你是不是没有缩小到正常尺寸


> 我设置loadStyle = GKPhotoBrowserLoadStyleIndeterminateMask还是没复现，你是不是没有缩小到正常尺寸



> 我设置loadStyle = GKPhotoBrowserLoadStyleIndeterminateMask还是没复现，你是不是没有缩小到正常尺寸

**Comment by cao903775389** [comment]
> > 我设置loadStyle = GKPhotoBrowserLoadStyleIndeterminateMask还是没复现，你是不是没有缩小到正常尺寸

好像不是loadStyle造成的，是这个旋转的属性导致的，你在demo里试下这个，是可以必现的，捏合手势缩放然后恢复
<img width="934" alt="WX20190702-142308@2x" src="https://user-images.githubusercontent.com/8541526/60488603-f2adff80-9cd4-11e9-8995-104bf5e814f8.png">

**Comment by QuintGao** [comment]
最新版已修复该问题
