### ISSUE TITLE
pod install 问题

### ISSUE THREAD

**Issue by lancelot9527** [QuintGao/GKPhotoBrowser#53]
`'FLAnimatedImage/FLAnimatedImage.h' file not found` 最新版不会自动导入 FLAnimatedImage，`pod 'GKPhotoBrowser', '~> 1.2.2'` 就可以

**Comment by lancelot9527** [comment]
看了你的更新记录说是移除了，但安装最新的版本，还是有引用导致报错。 2018.08.07  1、移除FLAnimationImage

**Comment by QuintGao** [comment]
FLAnimationImage已经移除了
