### ISSUE TITLE
长图，父视图固定宽高，浏览，返回后，视图会闪动

### ISSUE THREAD

**Issue by liqian460385335** [QuintGao/GKPhotoBrowser#61]
长图浏览，浏览页消失后，父视图会闪动

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo作者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA
