### ISSUE TITLE
在ios13下，拖动图片返回的时候，背景是全黑的，而不是原来那种渐变为透明。

### ISSUE THREAD

**Issue by melody1237** [QuintGao/GKPhotoBrowser#62]

**Comment by QuintGao** [comment]
我这没问题啊，你在什么情况下使用的

**Comment by QuintGao** [comment]
iOS13下不要修改GKPhotoBrowser的modalPresentationStyle

**Comment by melody1237** [comment]
确实是这个引起的，非常感谢您的解答，谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"QuintGao"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月30日(星期一) 下午5:08
收件人:&nbsp;"QuintGao/GKPhotoBrowser"<GKPhotoBrowser@noreply.github.com&gt;;
抄送:&nbsp;"赵世杰"<546213691@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [QuintGao/GKPhotoBrowser] 在ios13下，拖动图片返回的时候，背景是全黑的，而不是原来那种渐变为透明。 (#62)




iOS13下不要修改GKPhotoBrowser的modalPresentationStyle
