### ISSUE TITLE
编译报错，Xcode 11.2.1

### ISSUE THREAD

**Issue by Naruto-yq** [QuintGao/GKPhotoBrowser#65]
![image](https://user-images.githubusercontent.com/16412125/69129208-e7733900-0ae8-11ea-87bd-ad56b087606b.png)

**Comment by lawDavid** [comment]
那就改成assign，这个写法确实有问题。

**Comment by lawDavid** [comment]
那就改成assign，这个写法确实有问题。

**Comment by QuintGao** [comment]
最新版已修复
