### ISSUE TITLE
iOS 13.2.3 先查看崩溃

### ISSUE THREAD

**Issue by wcgCoding** [QuintGao/GKPhotoBrowser#67]
![image](https://user-images.githubusercontent.com/16463741/70370817-fc343700-1906-11ea-9abc-b03cb819951e.png)
1.先tableViewCell多图zoom 中查看图片，
2.在调用拍照，点击使用照片就崩溃闪退。
````
- (void)tabkePhoto {
    UIImagePickerControllerSourceType sourceType   = UIImagePickerControllerSourceTypeCamera;
    UIImagePickerController           *imagePicker = [UIImagePickerController new];
    imagePicker.delegate = self;
    imagePicker.sourceType             = sourceType;
    imagePicker.modalPresentationStyle = UIModalPresentationFullScreen;
    imagePicker.videoMaximumDuration   = 60;
    imagePicker.mediaTypes             = @[(NSString *)kUTTypeMovie, (NSString *)kUTTypeImage];
    [imagePicker setCameraDevice:UIImagePickerControllerCameraDeviceRear];
    [self presentViewController:imagePicker animated:YES completion:nil];
}
#pragma mark - UIImagePickerControllerDelegate
- (void)imagePickerController:(UIImagePickerController *)picker didFinishPickingMediaWithInfo:(NSDictionary *)info {
    [picker dismissViewControllerAnimated:YES completion:nil];
}

- (void)imagePickerControllerDidCancel:(UIImagePickerController *)picker {
    [self dismissViewControllerAnimated:YES completion:nil];
}

**Comment by wcgLR** [comment]
选择一张图片也会闪退。

**Comment by wcgLR** [comment]
经过测试这句代码删除注释就不会崩溃，endGeneratingDeviceOrientationNotifications

**Comment by wcgLR** [comment]
可以这样修改，如果外界已经产生旋转的通知就不用移除。
···
#pragma mark - 屏幕旋转相关
- (void)addDeviceOrientationObserver {
    // 默认设备方向：竖屏
    self.originalOrientation = UIDeviceOrientationPortrait;
    
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(deviceOrientationDidChange) name:UIDeviceOrientationDidChangeNotification object:nil];
    self.isGeneratingDeviceOrientationNotifications = [UIDevice currentDevice].isGeneratingDeviceOrientationNotifications;
    if (!self.isGeneratingDeviceOrientationNotifications) {
        [[UIDevice currentDevice] beginGeneratingDeviceOrientationNotifications];
    }
}

- (void)delDeviceOrientationObserver {
    [[NSNotificationCenter defaultCenter] removeObserver:self name:UIDeviceOrientationDidChangeNotification object:nil];
    if(!self.isGeneratingDeviceOrientationNotifications) {
        [[UIDevice currentDevice] endGeneratingDeviceOrientationNotifications];
    }
}
···

**Comment by QuintGao** [comment]
第1步，查看图片后GKPhotoBrowser销毁了没

**Comment by wcgLR** [comment]
销毁了啊

**Comment by chimingzi** [comment]
> 可以这样修改，如果外界已经产生旋转的通知就不用移除。
> 
> ```
> #pragma mark - 屏幕旋转相关
> - (void)addDeviceOrientationObserver {
>     // 默认设备方向：竖屏
>     self.originalOrientation = UIDeviceOrientationPortrait;
>     
>     [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(deviceOrientationDidChange) name:UIDeviceOrientationDidChangeNotification object:nil];
>     self.isGeneratingDeviceOrientationNotifications = [UIDevice currentDevice].isGeneratingDeviceOrientationNotifications;
>     if (!self.isGeneratingDeviceOrientationNotifications) {
>         [[UIDevice currentDevice] beginGeneratingDeviceOrientationNotifications];
>     }
> }
> 
> - (void)delDeviceOrientationObserver {
>     [[NSNotificationCenter defaultCenter] removeObserver:self name:UIDeviceOrientationDidChangeNotification object:nil];
>     if(!self.isGeneratingDeviceOrientationNotifications) {
>         [[UIDevice currentDevice] endGeneratingDeviceOrientationNotifications];
>     }
> }
> ```

同意你的判断，我初步测试也是因为beginGeneratingDeviceOrientationNotifications 和 endGeneratingDeviceOrientationNotifications两个方法没有成对调用导致的。
如果重复调用endGeneratingDeviceOrientationNotifications时，必然crash。
我是这么改的，和你的方式大同小异：

1.添加成员变量
```
/** 20200312 是否已经开始开始监听屏幕旋转。
 添加本参数的原因说明：
 由于iOS 13.x要求 endGeneratingDeviceOrientationNotifications
 和beginGeneratingDeviceOrientationNotifications 需要成对调用，如果已经调用过beginGeneratingDeviceOrientationNotifications，再次调用的话，会导致crash
 报错：NSInternalInconsistencyException原因：threading violation: expected the main thread
 **/
@property(nonatomic, assign) BOOL isGeneratingDeviceOrientationNotificationsBegun;
```

2.改造如下两个方法
```
#pragma mark - 屏幕旋转相关
- (void)addDeviceOrientationObserver {
    // 默认设备方向：竖屏
    self.originalOrientation = UIDeviceOrientationPortrait;
    
    if(!self.isGeneratingDeviceOrientationNotificationsBegun)
    {
        [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(deviceOrientationDidChange) name:UIDeviceOrientationDidChangeNotification object:nil];
        [[UIDevice currentDevice] beginGeneratingDeviceOrientationNotifications];
        self.isGeneratingDeviceOrientationNotificationsBegun = YES;
    }
}

- (void)delDeviceOrientationObserver {
    if(!self.isGeneratingDeviceOrientationNotificationsBegun)
        return;
    
    [[NSNotificationCenter defaultCenter] removeObserver:self name:UIDeviceOrientationDidChangeNotification object:nil];
    [[UIDevice currentDevice] endGeneratingDeviceOrientationNotifications];
    self.isGeneratingDeviceOrientationNotificationsBegun = NO;
}
```

**Comment by chimingzi** [comment]
> 销毁了啊

干脆弄了一下，PullRequest #72

1.修复在iOS13.x 下可能由于监听屏幕旋转导致app闪退的问题。
2.修复可能影响App本身的屏幕旋转监听的问题。
3.修复了可能存在多次addObserver导致deviceOrientationDidChange方法调用频次异常的问题。
