### ISSUE TITLE
屏幕旋转问题

### ISSUE THREAD

**Issue by LeeYZ** [QuintGao/GKPhotoBrowser#71]
GKPhotoBrowser dealloc的时候删除屏幕旋转监听，调用了endGeneratingDeviceOrientationNotifications，这样会影响到项目本身的旋转事件监听，麻烦验证一下

**Comment by chimingzi** [comment]
> GKPhotoBrowser dealloc的时候删除屏幕旋转监听，调用了endGeneratingDeviceOrientationNotifications，这样会影响到项目本身的旋转事件监听，麻烦验证一下

相信你已经解决了这个问题，还是给你个解决方案，请查看PullRequest #72
