### ISSUE TITLE
self.view.alpha = 0; 会出现一片空白的情况

### ISSUE THREAD

**Issue by ljj756640646** [QuintGao/GKPhotoBrowser#73]
if (photo.sourceImageView == nil) {
            [UIView animateWithDuration:kAnimationDuration animations:^{
                self.view.alpha = 0;// 改为1 
            }completion:^(BOOL finished) {
                [self dismissAnimated:NO];
            }];
            return;
        }

**Comment by QuintGao** [comment]
我这边没发现这个问题，有复现的demo吗
