### ISSUE TITLE
 横屏进入时，显示异常

### ISSUE THREAD

**Issue by QingyuHu** [QuintGao/GKPhotoBrowser#74]
第一次进入，如果是从横屏界面进入，会有一个旋转的动画，强制把图片旋转成竖屏。麻烦确认一下是否是我试用的有问题，还是确实存在这个bug

**Comment by QuintGao** [comment]
在APP支持横竖屏的时候确实会出现这个bug

**Comment by QuintGao** [comment]
最新版2.0.3 已适配，需要设置isFollowSystemRotation为YES
