### ISSUE TITLE
sd 能改成YYAnimatedImageView?

### ISSUE THREAD

**Issue by 986138497** [QuintGao/GKPhotoBrowser#76]
YYAnimatedImageView 可以支持 web 和普通图片和 gif ,这样省得导入太多

**Comment by QuintGao** [comment]
最新版已支持YYWebImage，可以使用pod 'GKPhotoBrowser/YY'

**Comment by 986138497** [comment]
好的,yywebimage 已经有人把 NSURLConnectionDelegate 改成NSURLSession,在 wiki 里面

**Comment by 986138497** [comment]
谢谢

**Comment by 986138497** [comment]
https://github.com/ibireme/YYKit/pull/489

**Comment by QuintGao** [comment]
嗯 如果要使用修改后的 只能自己导入了

**Comment by 986138497** [comment]
- (UIImage *)imageFromMemoryForURL:(NSURL *)url {
    YYWebImageManager *manager = [YYWebImageManager sharedManager];
    NSString *key = [manager cacheKeyForURL:url];
    return [manager.cache getImageForKey:key withType:YYImageCacheTypeMemory];
}
把 type 改成YYImageCacheTypeAll 是不是更好点

**Comment by QuintGao** [comment]
已优化
