### ISSUE TITLE
能否支持一下视频播放？

### ISSUE THREAD

**Issue by liuzhao** [QuintGao/GKPhotoBrowser#79]
这个相册做的非常好，在ZLPhotoBrowser的基础上增加了很多拓展项，特别是自定义view，唯一遗憾的就是ZLPhotoBrowser支持视频播放，您这框架是不是也加个支持视频播放的？这样就完美了！

**Comment by QuintGao** [comment]
最近比较忙，如果有需求，可以自己添加
