### ISSUE TITLE
与TZPickimageController有冲突

### ISSUE THREAD

**Issue by Mamakou** [QuintGao/GKPhotoBrowser#80]
经常性的打开TZPickimageController后，会报这个问题threading violation: expected the main thread，有人提出来是与GKPhotoBrowser有冲突才导致。我找不到问题再哪，还希望作者帮忙研究一下。谢谢

**Comment by QuintGao** [comment]
我这试了下，没发现这个问题，能找的复现的步骤吗，或者提供可复现的demo

**Comment by Mamakou** [comment]
额，这个是偶发性的。我也不好说呀

**Comment by QuintGao** [comment]
我想起来了，这个问题之前已经修复过了，是跟屏幕旋转监听方法有关，你看看最新的版本还会不会出现。

**Comment by Mamakou** [comment]
好的，谢谢，我先看下
