### ISSUE TITLE
maxZoomScale这个属性被你写死了

### ISSUE THREAD

**Issue by liuzhao** [QuintGao/GKPhotoBrowser#82]
既然在头文件里暴露出去了，那就不要在.m文件中写死maxZoomScale=kMaxZoomScale啊，要改动这个maxZoomScale还得改pod文件，这样就不好了。

**Comment by QuintGao** [comment]
这个属性默认是kMaxZoomScale，可以自行修改的

**Comment by liuzhao** [comment]
> 这个属性默认是kMaxZoomScale，可以自行修改的

改不了的，你的doubleZoomScale是可以改的，因为你写了setDoubleZoomScale，实际测试也是可以改双击的，但是maxZoomScale没重写赋值方法，实测改了没有作用。只能改pod里的kMaxZoomScale

**Comment by QuintGao** [comment]
具体修改可查看朋友圈那个demo

**Comment by liuzhao** [comment]
> 具体修改可查看朋友圈那个demo

好的，谢谢，我一开始的写法确实是跟朋友圈那个一样的，但是就是不起作用，刚才我又去试了，居然可以了。哎，不知道是不是我眼花了。
