### ISSUE TITLE
handleSingleTap的方法应该优化一下

### ISSUE THREAD

**Issue by liuzhao** [QuintGao/GKPhotoBrowser#83]
- (void)handleSingleTap:(UITapGestureRecognizer *)tap {
    if (self.isSingleTapDisabled) return;
    
    if ([self.delegate respondsToSelector:@selector(photoBrowser:singleTapWithIndex:)]) {
        [self.delegate photoBrowser:self singleTapWithIndex:self.currentIndex];
    }
    
    [self dismiss];
}
这段代码既然已经响应photoBrowser:singleTapWithIndex:了，就应该交由开发者去决定点击后的操作，所以应该在[self.delegate photoBrowser:self singleTapWithIndex:self.currentIndex];后加上return，否则的话，页面会直接消失。（纯属建议，我在使用过程中发现的，其实我本身就是不想他点击就消失才使用该代理的，结果还是点击就消失了）

**Comment by QuintGao** [comment]
最新版已优化

**Comment by liuzhao** [comment]
感谢作者！大赞！
