### ISSUE TITLE
是否可以适配一下iPad的屏幕旋转

### ISSUE THREAD

**Issue by pcccccc** [QuintGao/GKPhotoBrowser#84]
期望适配iPad的屏幕旋转，目前的屏幕旋转有bug。
版本：2.0.1
复现操作：横屏进入图片浏览后，会强制旋转到竖屏（图1）。反复旋转屏幕后左边会流出黑边（图2）。
![QQ20200611-154217](https://user-images.githubusercontent.com/13974510/84358776-36ee9300-abfa-11ea-8583-896973c2dd5b.png)
![QQ20200611-154044](https://user-images.githubusercontent.com/13974510/84358798-41109180-abfa-11ea-82d9-e39ab12cfd0c.png)

**Comment by QuintGao** [comment]
最新版2.0.3 已适配，需要设置isFollowSystemRotation为YES
