### ISSUE TITLE
请问一下，如果GIF是本地图片的话，如何支持gif动画？

### ISSUE THREAD

**Issue by liuzhao** [QuintGao/GKPhotoBrowser#86]
目前发现从本地导入的GIF图，无法显示动态效果，（图片后缀名是gif、GIF）。是否gif只支持网络在线URL形式的？

**Comment by QuintGao** [comment]
看朋友圈的demo

**Comment by liuzhao** [comment]
> 看第二个demo

额，demo是可以，我意思是你demo里的GKPhoto和pod库里的GKPhoto完全不一样，库里的GKPhoto少了很多东西，包括gif，而demo里的GKPhoto是有gifImage、isGif等属性的，但是pod库里的没有，这是怎么回事？

**Comment by liuzhao** [comment]
另外我发现demo上有的功能，pod里少了很多，比如pod库里的GKPhotoView甚至连加载网络gif的判断代码都没有，比如这段：if ([NSData sd_imageFormatForImageData:data] == SDImageFormatGIF)，是不是上传pod的时候漏提交了？

**Comment by QuintGao** [comment]
你下的不是最新版的demo吧，这些最新版已经去掉了

**Comment by liuzhao** [comment]
我更新成最新版demo，试了下本地gif，发现[YYImage imageNamed:obj];点开大图浏览后是可动的，但是使用[SDAnimatedImage imageNamed:obj];则是无效的。

**Comment by liuzhao** [comment]
我发现了SD不行的原因了，是因为demo里面下面没写[browser setupWebImageProtocol:[GKSDWebImageManager new]];这一段代码导致的😂。对了，demo里是有GKSDWebImageManager和GKYYWebImageManager的，但是pod库里却没有。以至于如果用pod方式集成进去后，还需要去下载源码找到这两个库才能加正常使用。

**Comment by QuintGao** [comment]
1、默认使用的就是GKSDWebImageManager，你把那句代码删了也可以。

**Comment by QuintGao** [comment]
1、默认使用的就是GKSDWebImageManager，你把那句代码删了也可以。
2、使用 pod 'GKPhotoBrowser' 默认会添加SDWebImage，如果你想使用YYWebImage，可以使用 pod 'GKPhotoBrowser/YY'
