### ISSUE TITLE
如果GKPhoto只设置了image，没有设置url，就无法双击放大

### ISSUE THREAD

**Issue by wkdwangjun** [QuintGao/GKPhotoBrowser#91]
如题。
简单的调试了下。发现双击放大的方法里有个条件是GKPhoto.finished为YES。通过image设定图片的，finished属性不会设置成YES。
`- (void)handleDoubleTap:(UITapGestureRecognizer *)tap {`
`    GKPhotoView *photoView = [self currentPhotoView];`
`    GKPhoto *photo = [self currentPhoto];`
`    `
`    if (!photo.finished) return;`
`...`

**Comment by QuintGao** [comment]
最新版2.0.8已修复
