### ISSUE TITLE
iOS 14 Bugs.

### ISSUE THREAD

**Issue by YangsCalvin** [QuintGao/GKPhotoBrowser#92]
iOS 14 上展示动画失效，并且图片加载不出来，呈现黑屏状态.

**Comment by QuintGao** [comment]
需要把SDWebImage升级到5.8.3版本

**Comment by JennyWXH** [comment]
> 需要把SDWebImage升级到5.8.3版本

你好，请问下为什么要升到5.8.3呢

**Comment by QuintGao** [comment]
SDAnimatedImageView 5.8.3以前的版本在iOS14上显示不了图片
