### ISSUE TITLE
加载放在沙盒里的图片，多了会造成内存暴增闪退

### ISSUE THREAD

**Issue by liuzhao** [QuintGao/GKPhotoBrowser#93]
如果加载的图片来自本地沙盒，比如加载100张左右，从第一张开始往后滑动，滑到一半的时候内存就开始吃不消了，会出现“[Unknown process name] CGSImageDataLock: Cannot allocate memory”之类的提示，然后最终闪退，不知道有没有办法解决这个问题？

**Comment by QuintGao** [comment]
有没有demo我试下

**Comment by AlianOL** [comment]
> 如果加载的图片来自本地沙盒，比如加载100张左右，从第一张开始往后滑动，滑到一半的时候内存就开始吃不消了，会出现“[Unknown process name] CGSImageDataLock: Cannot allocate memory”之类的提示，然后最终闪退，不知道有没有办法解决这个问题？

我觉得这个是sdwebimage的问题，好像是开辟的线程数量太多了，没有加载过来？

**Comment by QuintGao** [comment]
最新版已优化
