### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by zsfy** [QuintGao/GKPhotoBrowser#96]
新建工程，通过cocoapods集成，任意一个按钮，添加以下代码。

 GKPhoto *photo = [GKPhoto new];
 photo.url = [NSURL URLWithString:@"http://ww3.sinaimg.cn/thumbnail/006ka0Iygw1f6bqm7zukpj30g60kzdi2.jpg"];
 photo.originUrl = [NSURL URLWithString:@"http://ww3.sinaimg.cn/large/006ka0Iygw1f6bqm7zukpj30g60kzdi2.jpg"];
 NSMutableArray *photos = [NSMutableArray new];
 [photos addObject:photo];
 GKPhotoBrowser *browser = [GKPhotoBrowser photoBrowserWithPhotos:photos currentIndex:0];
  [browser showFromVC:self];

单击消失GKPhotoBrowser后，GKPhotoBrowser未释放

版本信息如下：
Installing GKPhotoBrowser (2.0.8)
Installing SDWebImage (5.8.4)

**Comment by QuintGao** [comment]
刚试了下 没问题，可以释放啊

**Comment by zsfy** [comment]
我把视频上传百度网盘了，你看一下 链接: https://pan.baidu.com/s/1cp-wk4YX9yZYb4izdp3T1g 提取码: 8pwp
Xcode Version 11.5 (11E608c),

**Comment by zsfy** [comment]
[leak.zip](https://github.com/QuintGao/GKPhotoBrowser/files/5198887/leak.zip)

**Comment by QuintGao** [comment]
我用你的demo也是释放了的，Xcode Version 11.7 (11E801a)

**Comment by zsfy** [comment]
我重新下载后确实释放了，但是我没改任何代码或设置。
