### ISSUE TITLE
Pod到最新的版本加载图片无效

### ISSUE THREAD

**Issue by ljbshishabi** [QuintGao/GKPhotoBrowser#97]
NSMutableArray *photos = [NSMutableArray new];
    
    for (NSString *url in @[@"https://ss0.bdstatic.com/94oJfD_bAAcT8t7mm9GUKT-xh_/timg?image&quality=100&size=b4000_4000&sec=1600345840&di=c72e6b3608f2e1d6d94d72ac5488f33d&src=http://a2.att.hudong.com/36/48/19300001357258133412489354717.jpg",@"https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1600355923356&di=ff9f264ec7b2d3df605a75bf494b2cf4&imgtype=0&src=http%3A%2F%2Fa3.att.hudong.com%2F14%2F75%2F01300000164186121366756803686.jpg"])
    {
        GKPhoto *photo = [GKPhoto new];
        photo.url = [NSURL URLWithString:url];
        [photos addObject:photo];
    }
    
    GKPhotoBrowser *browser = [GKPhotoBrowser photoBrowserWithPhotos:photos currentIndex:0];
    browser.showStyle = GKPhotoBrowserShowStyleZoom;        // 缩放显示
    browser.hideStyle = GKPhotoBrowserHideStyleZoomScale;   // 缩放隐藏
    browser.loadStyle = GKPhotoBrowserLoadStyleDeterminate;
    browser.failStyle       = GKPhotoBrowserFailStyleOnlyImage;
    browser.failureText     = @"图片加载失败了，555";
    browser.failureImage    = [UIImage imageNamed:@"error"];

    [browser showFromVC:self];

使用最基本的加载方式 图片出不来。 控制器出来了 错误提示全部没有。是我有什么地方没设置吗？

**Comment by ljbshishabi** [comment]
Demo中的test02里。section为2的cell里面的数据我这边也显示不了。点击之后GKPhotoBrowser出现，但是图片没有出来，只是一片黑。手势还是有效

**Comment by ljbshishabi** [comment]
环境是iOS14-模拟器&iPhoneX

**Comment by QuintGao** [comment]
SDWebImage用的哪个版本

**Comment by ljbshishabi** [comment]
5.8.0的版本

**Comment by QuintGao** [comment]
#92
